// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: driver.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createDriver = `-- name: CreateDriver :one

INSERT INTO drivers (
    user_id,
    license_number,
    license_expiry,
    vehicle_type,
    vehicle_plate,
    vehicle_capacity,
    status,
    background_check_status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, user_id, license_number, license_expiry, vehicle_type, vehicle_plate, vehicle_capacity, status, rating, total_deliveries, background_check_status, background_check_date, created_at, updated_at, driver_id
`

type CreateDriverParams struct {
	UserID                string    `json:"user_id"`
	LicenseNumber         string    `json:"license_number"`
	LicenseExpiry         time.Time `json:"license_expiry"`
	VehicleType           string    `json:"vehicle_type"`
	VehiclePlate          string    `json:"vehicle_plate"`
	VehicleCapacity       string    `json:"vehicle_capacity"`
	Status                string    `json:"status"`
	BackgroundCheckStatus string    `json:"background_check_status"`
}

// ============================================
// DRIVER QUERIES
// ============================================
func (q *Queries) CreateDriver(ctx context.Context, arg CreateDriverParams) (Driver, error) {
	row := q.db.QueryRowContext(ctx, createDriver,
		arg.UserID,
		arg.LicenseNumber,
		arg.LicenseExpiry,
		arg.VehicleType,
		arg.VehiclePlate,
		arg.VehicleCapacity,
		arg.Status,
		arg.BackgroundCheckStatus,
	)
	var i Driver
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LicenseNumber,
		&i.LicenseExpiry,
		&i.VehicleType,
		&i.VehiclePlate,
		&i.VehicleCapacity,
		&i.Status,
		&i.Rating,
		&i.TotalDeliveries,
		&i.BackgroundCheckStatus,
		&i.BackgroundCheckDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DriverID,
	)
	return i, err
}

const getDriver = `-- name: GetDriver :one
SELECT id, user_id, license_number, license_expiry, vehicle_type, vehicle_plate, vehicle_capacity, status, rating, total_deliveries, background_check_status, background_check_date, created_at, updated_at, driver_id FROM drivers
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDriver(ctx context.Context, id uuid.UUID) (Driver, error) {
	row := q.db.QueryRowContext(ctx, getDriver, id)
	var i Driver
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LicenseNumber,
		&i.LicenseExpiry,
		&i.VehicleType,
		&i.VehiclePlate,
		&i.VehicleCapacity,
		&i.Status,
		&i.Rating,
		&i.TotalDeliveries,
		&i.BackgroundCheckStatus,
		&i.BackgroundCheckDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DriverID,
	)
	return i, err
}

const getDriverByDriverID = `-- name: GetDriverByDriverID :one
SELECT id, user_id, license_number, license_expiry, vehicle_type, vehicle_plate, vehicle_capacity, status, rating, total_deliveries, background_check_status, background_check_date, created_at, updated_at, driver_id FROM drivers
WHERE driver_id = $1 LIMIT 1
`

func (q *Queries) GetDriverByDriverID(ctx context.Context, driverID string) (Driver, error) {
	row := q.db.QueryRowContext(ctx, getDriverByDriverID, driverID)
	var i Driver
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LicenseNumber,
		&i.LicenseExpiry,
		&i.VehicleType,
		&i.VehiclePlate,
		&i.VehicleCapacity,
		&i.Status,
		&i.Rating,
		&i.TotalDeliveries,
		&i.BackgroundCheckStatus,
		&i.BackgroundCheckDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DriverID,
	)
	return i, err
}

const getDriverByUserID = `-- name: GetDriverByUserID :one
SELECT id, user_id, license_number, license_expiry, vehicle_type, vehicle_plate, vehicle_capacity, status, rating, total_deliveries, background_check_status, background_check_date, created_at, updated_at, driver_id FROM drivers
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetDriverByUserID(ctx context.Context, userID string) (Driver, error) {
	row := q.db.QueryRowContext(ctx, getDriverByUserID, userID)
	var i Driver
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LicenseNumber,
		&i.LicenseExpiry,
		&i.VehicleType,
		&i.VehiclePlate,
		&i.VehicleCapacity,
		&i.Status,
		&i.Rating,
		&i.TotalDeliveries,
		&i.BackgroundCheckStatus,
		&i.BackgroundCheckDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DriverID,
	)
	return i, err
}

const getDriverWithUser = `-- name: GetDriverWithUser :one
SELECT 
    d.id, d.user_id, d.license_number, d.license_expiry, d.vehicle_type, d.vehicle_plate, d.vehicle_capacity, d.status, d.rating, d.total_deliveries, d.background_check_status, d.background_check_date, d.created_at, d.updated_at, d.driver_id,
    u.first_name,
    u.last_name,
    u.email,
    u.phone,
    u.avatar
FROM drivers d
INNER JOIN users u ON d.user_id = u.user_id
WHERE d.driver_id = $1
LIMIT 1
`

type GetDriverWithUserRow struct {
	ID                    uuid.UUID      `json:"id"`
	UserID                string         `json:"user_id"`
	LicenseNumber         string         `json:"license_number"`
	LicenseExpiry         time.Time      `json:"license_expiry"`
	VehicleType           string         `json:"vehicle_type"`
	VehiclePlate          string         `json:"vehicle_plate"`
	VehicleCapacity       string         `json:"vehicle_capacity"`
	Status                string         `json:"status"`
	Rating                sql.NullString `json:"rating"`
	TotalDeliveries       sql.NullInt32  `json:"total_deliveries"`
	BackgroundCheckStatus string         `json:"background_check_status"`
	BackgroundCheckDate   sql.NullTime   `json:"background_check_date"`
	CreatedAt             time.Time      `json:"created_at"`
	UpdatedAt             time.Time      `json:"updated_at"`
	DriverID              string         `json:"driver_id"`
	FirstName             string         `json:"first_name"`
	LastName              string         `json:"last_name"`
	Email                 string         `json:"email"`
	Phone                 string         `json:"phone"`
	Avatar                sql.NullString `json:"avatar"`
}

func (q *Queries) GetDriverWithUser(ctx context.Context, driverID string) (GetDriverWithUserRow, error) {
	row := q.db.QueryRowContext(ctx, getDriverWithUser, driverID)
	var i GetDriverWithUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LicenseNumber,
		&i.LicenseExpiry,
		&i.VehicleType,
		&i.VehiclePlate,
		&i.VehicleCapacity,
		&i.Status,
		&i.Rating,
		&i.TotalDeliveries,
		&i.BackgroundCheckStatus,
		&i.BackgroundCheckDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DriverID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Avatar,
	)
	return i, err
}

const listAvailableDrivers = `-- name: ListAvailableDrivers :many
SELECT id, user_id, license_number, license_expiry, vehicle_type, vehicle_plate, vehicle_capacity, status, rating, total_deliveries, background_check_status, background_check_date, created_at, updated_at, driver_id FROM drivers
WHERE status = 'online'
AND background_check_status = 'approved'
ORDER BY rating DESC, total_deliveries DESC
`

func (q *Queries) ListAvailableDrivers(ctx context.Context) ([]Driver, error) {
	rows, err := q.db.QueryContext(ctx, listAvailableDrivers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Driver{}
	for rows.Next() {
		var i Driver
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LicenseNumber,
			&i.LicenseExpiry,
			&i.VehicleType,
			&i.VehiclePlate,
			&i.VehicleCapacity,
			&i.Status,
			&i.Rating,
			&i.TotalDeliveries,
			&i.BackgroundCheckStatus,
			&i.BackgroundCheckDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DriverID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDriversByVehicleType = `-- name: ListDriversByVehicleType :many
SELECT id, user_id, license_number, license_expiry, vehicle_type, vehicle_plate, vehicle_capacity, status, rating, total_deliveries, background_check_status, background_check_date, created_at, updated_at, driver_id FROM drivers
WHERE vehicle_type = $1
AND status = 'online'
ORDER BY rating DESC
`

func (q *Queries) ListDriversByVehicleType(ctx context.Context, vehicleType string) ([]Driver, error) {
	rows, err := q.db.QueryContext(ctx, listDriversByVehicleType, vehicleType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Driver{}
	for rows.Next() {
		var i Driver
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LicenseNumber,
			&i.LicenseExpiry,
			&i.VehicleType,
			&i.VehiclePlate,
			&i.VehicleCapacity,
			&i.Status,
			&i.Rating,
			&i.TotalDeliveries,
			&i.BackgroundCheckStatus,
			&i.BackgroundCheckDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DriverID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDriver = `-- name: UpdateDriver :one
UPDATE drivers
SET 
    license_number = COALESCE($2, license_number),
    license_expiry = COALESCE($3, license_expiry),
    vehicle_type = COALESCE($4, vehicle_type),
    vehicle_plate = COALESCE($5, vehicle_plate),
    vehicle_capacity = COALESCE($6, vehicle_capacity),
    status = COALESCE($7, status),
    background_check_status = COALESCE($8, background_check_status),
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, license_number, license_expiry, vehicle_type, vehicle_plate, vehicle_capacity, status, rating, total_deliveries, background_check_status, background_check_date, created_at, updated_at, driver_id
`

type UpdateDriverParams struct {
	ID                    uuid.UUID `json:"id"`
	LicenseNumber         string    `json:"license_number"`
	LicenseExpiry         time.Time `json:"license_expiry"`
	VehicleType           string    `json:"vehicle_type"`
	VehiclePlate          string    `json:"vehicle_plate"`
	VehicleCapacity       string    `json:"vehicle_capacity"`
	Status                string    `json:"status"`
	BackgroundCheckStatus string    `json:"background_check_status"`
}

func (q *Queries) UpdateDriver(ctx context.Context, arg UpdateDriverParams) (Driver, error) {
	row := q.db.QueryRowContext(ctx, updateDriver,
		arg.ID,
		arg.LicenseNumber,
		arg.LicenseExpiry,
		arg.VehicleType,
		arg.VehiclePlate,
		arg.VehicleCapacity,
		arg.Status,
		arg.BackgroundCheckStatus,
	)
	var i Driver
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LicenseNumber,
		&i.LicenseExpiry,
		&i.VehicleType,
		&i.VehiclePlate,
		&i.VehicleCapacity,
		&i.Status,
		&i.Rating,
		&i.TotalDeliveries,
		&i.BackgroundCheckStatus,
		&i.BackgroundCheckDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DriverID,
	)
	return i, err
}

const updateDriverRating = `-- name: UpdateDriverRating :exec
UPDATE drivers
SET 
    rating = $2,
    total_deliveries = total_deliveries + 1,
    updated_at = now()
WHERE driver_id = $1
`

type UpdateDriverRatingParams struct {
	DriverID string         `json:"driver_id"`
	Rating   sql.NullString `json:"rating"`
}

func (q *Queries) UpdateDriverRating(ctx context.Context, arg UpdateDriverRatingParams) error {
	_, err := q.db.ExecContext(ctx, updateDriverRating, arg.DriverID, arg.Rating)
	return err
}

const updateDriverStatus = `-- name: UpdateDriverStatus :exec
UPDATE drivers
SET 
    status = $2,
    updated_at = now()
WHERE driver_id = $1
`

type UpdateDriverStatusParams struct {
	DriverID string `json:"driver_id"`
	Status   string `json:"status"`
}

func (q *Queries) UpdateDriverStatus(ctx context.Context, arg UpdateDriverStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateDriverStatus, arg.DriverID, arg.Status)
	return err
}
