// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Address struct {
	ID     uuid.UUID `json:"id"`
	UserID string    `json:"user_id"`
	// home, office, warehouse, etc
	Label         sql.NullString `json:"label"`
	StreetAddress string         `json:"street_address"`
	City          string         `json:"city"`
	State         string         `json:"state"`
	PostalCode    string         `json:"postal_code"`
	Country       string         `json:"country"`
	Latitude      sql.NullString `json:"latitude"`
	Longitude     sql.NullString `json:"longitude"`
	// delivery instructions
	Instructions sql.NullString `json:"instructions"`
	IsDefault    sql.NullBool   `json:"is_default"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	AddressID    string         `json:"address_id"`
}

type Customer struct {
	ID          uuid.UUID      `json:"id"`
	UserID      string         `json:"user_id"`
	CompanyName sql.NullString `json:"company_name"`
	// individual, business, enterprise
	BusinessType   sql.NullString `json:"business_type"`
	BillingAddress string         `json:"billing_address"`
	// credit_card, debit_card, wallet, invoice
	PaymentMethod sql.NullString `json:"payment_method"`
	CreditLimit   sql.NullString `json:"credit_limit"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	CustomerID    string         `json:"customer_id"`
}

type Delivery struct {
	ID                    uuid.UUID      `json:"id"`
	PackageID             string         `json:"package_id"`
	DriverID              sql.NullString `json:"driver_id"`
	RouteID               sql.NullString `json:"route_id"`
	ScheduledPickupTime   sql.NullTime   `json:"scheduled_pickup_time"`
	ActualPickupTime      sql.NullTime   `json:"actual_pickup_time"`
	ScheduledDeliveryTime sql.NullTime   `json:"scheduled_delivery_time"`
	EstimatedDeliveryTime sql.NullTime   `json:"estimated_delivery_time"`
	ActualDeliveryTime    sql.NullTime   `json:"actual_delivery_time"`
	// assigned, in_progress, completed, failed, cancelled
	DeliveryStatus string `json:"delivery_status"`
	// signature or photo URL
	DeliveryProof   sql.NullString `json:"delivery_proof"`
	DeliveryNotes   sql.NullString `json:"delivery_notes"`
	FailureReason   sql.NullString `json:"failure_reason"`
	DistanceKm      sql.NullString `json:"distance_km"`
	DurationMinutes sql.NullInt32  `json:"duration_minutes"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	DeliveryID      string         `json:"delivery_id"`
}

type Driver struct {
	ID            uuid.UUID `json:"id"`
	UserID        string    `json:"user_id"`
	LicenseNumber string    `json:"license_number"`
	LicenseExpiry time.Time `json:"license_expiry"`
	// motorcycle, car, van, truck
	VehicleType  string `json:"vehicle_type"`
	VehiclePlate string `json:"vehicle_plate"`
	// in kg or cubic meters
	VehicleCapacity string `json:"vehicle_capacity"`
	// online, offline, on_delivery, break
	Status string `json:"status"`
	// average rating out of 5
	Rating          sql.NullString `json:"rating"`
	TotalDeliveries sql.NullInt32  `json:"total_deliveries"`
	// pending, approved, rejected
	BackgroundCheckStatus string       `json:"background_check_status"`
	BackgroundCheckDate   sql.NullTime `json:"background_check_date"`
	CreatedAt             time.Time    `json:"created_at"`
	UpdatedAt             time.Time    `json:"updated_at"`
	DriverID              string       `json:"driver_id"`
}

type DriverLocation struct {
	ID        uuid.UUID `json:"id"`
	DriverID  string    `json:"driver_id"`
	Latitude  string    `json:"latitude"`
	Longitude string    `json:"longitude"`
	// direction in degrees
	Heading sql.NullString `json:"heading"`
	// speed in km/h
	Speed sql.NullString `json:"speed"`
	// GPS accuracy in meters
	Accuracy     sql.NullString `json:"accuracy"`
	BatteryLevel sql.NullInt32  `json:"battery_level"`
	RecordedAt   time.Time      `json:"recorded_at"`
	CreatedAt    time.Time      `json:"created_at"`
	LocationID   string         `json:"location_id"`
}

type Notification struct {
	ID     uuid.UUID `json:"id"`
	UserID string    `json:"user_id"`
	// package_update, delivery_assigned, delivery_completed, etc
	NotificationType string `json:"notification_type"`
	Title            string `json:"title"`
	Message          string `json:"message"`
	// package_id, delivery_id, etc
	ReferenceID    sql.NullString `json:"reference_id"`
	IsRead         sql.NullBool   `json:"is_read"`
	SentAt         time.Time      `json:"sent_at"`
	ReadAt         sql.NullTime   `json:"read_at"`
	CreatedAt      time.Time      `json:"created_at"`
	NotificationID string         `json:"notification_id"`
}

type Package struct {
	ID             uuid.UUID `json:"id"`
	CustomerID     string    `json:"customer_id"`
	TrackingNumber string    `json:"tracking_number"`
	Description    string    `json:"description"`
	// in kg
	Weight string `json:"weight"`
	// LxWxH in cm
	Dimensions sql.NullString `json:"dimensions"`
	// documents, electronics, food, fragile, etc
	Category string `json:"category"`
	// declared value for insurance
	Value sql.NullString `json:"value"`
	// express, standard, economy
	Priority string `json:"priority"`
	// fragile, perishable, hazardous, etc
	SpecialHandling   sql.NullString `json:"special_handling"`
	PickupAddressID   string         `json:"pickup_address_id"`
	DeliveryAddressID string         `json:"delivery_address_id"`
	// pending, picked_up, in_transit, out_for_delivery, delivered, failed, cancelled
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	PackageID string    `json:"package_id"`
}

type Payment struct {
	ID            uuid.UUID      `json:"id"`
	CustomerID    string         `json:"customer_id"`
	DeliveryID    sql.NullString `json:"delivery_id"`
	Amount        string         `json:"amount"`
	Currency      string         `json:"currency"`
	PaymentMethod string         `json:"payment_method"`
	TransactionID sql.NullString `json:"transaction_id"`
	// pending, completed, failed, refunded
	Status      string       `json:"status"`
	PaymentDate sql.NullTime `json:"payment_date"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
	PaymentID   string       `json:"payment_id"`
}

type Pricing struct {
	ID         uuid.UUID `json:"id"`
	BasePrice  string    `json:"base_price"`
	PricePerKm string    `json:"price_per_km"`
	PricePerKg string    `json:"price_per_kg"`
	// express=2.0, standard=1.0, economy=0.8
	PriorityMultiplier string `json:"priority_multiplier"`
	// urban, suburban, rural
	Zone          string       `json:"zone"`
	EffectiveFrom time.Time    `json:"effective_from"`
	EffectiveTo   sql.NullTime `json:"effective_to"`
	CreatedAt     time.Time    `json:"created_at"`
	UpdatedAt     time.Time    `json:"updated_at"`
	PricingID     string       `json:"pricing_id"`
}

type Rating struct {
	ID         uuid.UUID `json:"id"`
	DeliveryID string    `json:"delivery_id"`
	// user_id of customer or driver
	RatedBy string `json:"rated_by"`
	// user_id being rated
	RatedUser string `json:"rated_user"`
	// 1-5 stars
	Rating  int32          `json:"rating"`
	Comment sql.NullString `json:"comment"`
	// driver_rating, customer_rating
	RatingType string    `json:"rating_type"`
	CreatedAt  time.Time `json:"created_at"`
	RatingID   string    `json:"rating_id"`
}

type Route struct {
	ID            uuid.UUID      `json:"id"`
	DriverID      string         `json:"driver_id"`
	RouteName     sql.NullString `json:"route_name"`
	StartLocation string         `json:"start_location"`
	EndLocation   sql.NullString `json:"end_location"`
	// planned, in_progress, completed, cancelled
	Status                   string         `json:"status"`
	TotalDistanceKm          sql.NullString `json:"total_distance_km"`
	EstimatedDurationMinutes sql.NullInt32  `json:"estimated_duration_minutes"`
	ActualDurationMinutes    sql.NullInt32  `json:"actual_duration_minutes"`
	// route efficiency score
	OptimizationScore sql.NullString `json:"optimization_score"`
	StartedAt         sql.NullTime   `json:"started_at"`
	CompletedAt       sql.NullTime   `json:"completed_at"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	RouteID           string         `json:"route_id"`
}

type RouteStop struct {
	ID         uuid.UUID `json:"id"`
	RouteID    string    `json:"route_id"`
	DeliveryID string    `json:"delivery_id"`
	// order of stops in the route
	StopSequence int32 `json:"stop_sequence"`
	// pickup, delivery
	StopType           string       `json:"stop_type"`
	AddressID          string       `json:"address_id"`
	ScheduledArrival   sql.NullTime `json:"scheduled_arrival"`
	ActualArrival      sql.NullTime `json:"actual_arrival"`
	ScheduledDeparture sql.NullTime `json:"scheduled_departure"`
	ActualDeparture    sql.NullTime `json:"actual_departure"`
	// pending, arrived, completed, skipped
	Status string `json:"status"`
	// time spent at stop
	DwellTimeMinutes sql.NullInt32 `json:"dwell_time_minutes"`
	CreatedAt        time.Time     `json:"created_at"`
	UpdatedAt        time.Time     `json:"updated_at"`
	StopID           string        `json:"stop_id"`
}

type TrackingEvent struct {
	ID         uuid.UUID      `json:"id"`
	PackageID  string         `json:"package_id"`
	DeliveryID sql.NullString `json:"delivery_id"`
	// created, assigned, picked_up, in_transit, out_for_delivery, delivered, exception
	EventType        string         `json:"event_type"`
	EventDescription string         `json:"event_description"`
	Location         sql.NullString `json:"location"`
	Latitude         sql.NullString `json:"latitude"`
	Longitude        sql.NullString `json:"longitude"`
	OccurredAt       time.Time      `json:"occurred_at"`
	// user_id who created the event
	CreatedBy sql.NullString `json:"created_by"`
	CreatedAt time.Time      `json:"created_at"`
	EventID   string         `json:"event_id"`
}

type User struct {
	ID        uuid.UUID      `json:"id"`
	FirstName string         `json:"first_name"`
	LastName  string         `json:"last_name"`
	Email     string         `json:"email"`
	Password  string         `json:"password"`
	Phone     string         `json:"phone"`
	Avatar    sql.NullString `json:"avatar"`
	// admin, dispatcher, customer, driver
	Role string `json:"role"`
	// active, suspended, inactive
	Status       string         `json:"status"`
	Token        sql.NullString `json:"token"`
	RefreshToken sql.NullString `json:"refresh_token"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	UserID       string         `json:"user_id"`
}

type VehicleMaintenance struct {
	ID       uuid.UUID `json:"id"`
	DriverID string    `json:"driver_id"`
	// inspection, repair, service
	MaintenanceType string         `json:"maintenance_type"`
	Description     string         `json:"description"`
	Cost            sql.NullString `json:"cost"`
	ScheduledDate   sql.NullTime   `json:"scheduled_date"`
	CompletedDate   sql.NullTime   `json:"completed_date"`
	NextDueDate     sql.NullTime   `json:"next_due_date"`
	// scheduled, completed, overdue
	Status        string    `json:"status"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
	MaintenanceID string    `json:"maintenance_id"`
}
