// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// ============================================
	// CUSTOMER QUERIES
	// ============================================
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	// ============================================
	// DRIVER QUERIES
	// ============================================
	CreateDriver(ctx context.Context, arg CreateDriverParams) (Driver, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeactivateUser(ctx context.Context, id uuid.UUID) (User, error)
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetCustomer(ctx context.Context, id uuid.UUID) (Customer, error)
	GetCustomerByCustomerID(ctx context.Context, customerID string) (Customer, error)
	GetCustomerByUserID(ctx context.Context, userID string) (Customer, error)
	GetCustomerWithUser(ctx context.Context, customerID string) (GetCustomerWithUserRow, error)
	GetDriver(ctx context.Context, id uuid.UUID) (Driver, error)
	GetDriverByDriverID(ctx context.Context, driverID string) (Driver, error)
	GetDriverByUserID(ctx context.Context, userID string) (Driver, error)
	GetDriverWithUser(ctx context.Context, driverID string) (GetDriverWithUserRow, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByEmailForUpdate(ctx context.Context, email string) (User, error)
	GetUserByUserID(ctx context.Context, userID string) (User, error)
	GetUserByUserIDForUpdate(ctx context.Context, userID string) (User, error)
	GetUserForUpdate(ctx context.Context, id uuid.UUID) (User, error)
	ListAvailableDrivers(ctx context.Context) ([]Driver, error)
	ListDriversByVehicleType(ctx context.Context, vehicleType string) ([]Driver, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ListUsersByRole(ctx context.Context, role string) ([]User, error)
	UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error)
	UpdateDriver(ctx context.Context, arg UpdateDriverParams) (Driver, error)
	UpdateDriverRating(ctx context.Context, arg UpdateDriverRatingParams) error
	UpdateDriverStatus(ctx context.Context, arg UpdateDriverStatusParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserTokens(ctx context.Context, arg UpdateUserTokensParams) error
}

var _ Querier = (*Queries)(nil)
