// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUserSession = `-- name: CreateUserSession :one

INSERT INTO user_sessions (
    user_id,
    session_token,
    expires_at
) VALUES (
    $1, $2, $3
)
RETURNING id, user_id, session_token, status, created_at, expires_at
`

type CreateUserSessionParams struct {
	UserID       string    `json:"user_id"`
	SessionToken string    `json:"session_token"`
	ExpiresAt    time.Time `json:"expires_at"`
}

// ============================================
// USER SESSIONS QUERIES
// ============================================
func (q *Queries) CreateUserSession(ctx context.Context, arg CreateUserSessionParams) (UserSession, error) {
	row := q.db.QueryRowContext(ctx, createUserSession, arg.UserID, arg.SessionToken, arg.ExpiresAt)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionToken,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteUserSession = `-- name: DeleteUserSession :exec
DELETE FROM user_sessions
WHERE id = $1
`

func (q *Queries) DeleteUserSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUserSession, id)
	return err
}

const getUserSession = `-- name: GetUserSession :one
SELECT id, user_id, session_token, status, created_at, expires_at FROM user_sessions
WHERE session_token = $1 AND expires_at = $2  LIMIT 1
`

type GetUserSessionParams struct {
	SessionToken string    `json:"session_token"`
	ExpiresAt    time.Time `json:"expires_at"`
}

func (q *Queries) GetUserSession(ctx context.Context, arg GetUserSessionParams) (UserSession, error) {
	row := q.db.QueryRowContext(ctx, getUserSession, arg.SessionToken, arg.ExpiresAt)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionToken,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

// UserSession represents a row from 'user_sessions' table