// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    first_name,
    last_name,
    email,
    password,
    phone,
    role,
    status,
    avatar
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, first_name, last_name, email, password, phone, avatar, role, status, token, refresh_token, created_at, updated_at, user_id
`

type CreateUserParams struct {
	FirstName string         `json:"first_name"`
	LastName  string         `json:"last_name"`
	Email     string         `json:"email"`
	Password  string         `json:"password"`
	Phone     string         `json:"phone"`
	Role      string         `json:"role"`
	Status    string         `json:"status"`
	Avatar    sql.NullString `json:"avatar"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Password,
		arg.Phone,
		arg.Role,
		arg.Status,
		arg.Avatar,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.Avatar,
		&i.Role,
		&i.Status,
		&i.Token,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const deactivateUser = `-- name: DeactivateUser :one
UPDATE users
SET 
    status = 'inactive',
    updated_at = now()
WHERE id = $1
RETURNING id, first_name, last_name, email, password, phone, avatar, role, status, token, refresh_token, created_at, updated_at, user_id
`

func (q *Queries) DeactivateUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, deactivateUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.Avatar,
		&i.Role,
		&i.Status,
		&i.Token,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, first_name, last_name, email, password, phone, avatar, role, status, token, refresh_token, created_at, updated_at, user_id FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.Avatar,
		&i.Role,
		&i.Status,
		&i.Token,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, first_name, last_name, email, password, phone, avatar, role, status, token, refresh_token, created_at, updated_at, user_id FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.Avatar,
		&i.Role,
		&i.Status,
		&i.Token,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const getUserByEmailForUpdate = `-- name: GetUserByEmailForUpdate :one
SELECT id, first_name, last_name, email, password, phone, avatar, role, status, token, refresh_token, created_at, updated_at, user_id FROM users
WHERE email = $1 LIMIT 1
FOR UPDATE
`

func (q *Queries) GetUserByEmailForUpdate(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmailForUpdate, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.Avatar,
		&i.Role,
		&i.Status,
		&i.Token,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const getUserByUserID = `-- name: GetUserByUserID :one
SELECT id, first_name, last_name, email, password, phone, avatar, role, status, token, refresh_token, created_at, updated_at, user_id FROM users
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetUserByUserID(ctx context.Context, userID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUserID, userID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.Avatar,
		&i.Role,
		&i.Status,
		&i.Token,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const getUserByUserIDForUpdate = `-- name: GetUserByUserIDForUpdate :one
SELECT id, first_name, last_name, email, password, phone, avatar, role, status, token, refresh_token, created_at, updated_at, user_id FROM users
WHERE user_id = $1 LIMIT 1
FOR UPDATE
`

func (q *Queries) GetUserByUserIDForUpdate(ctx context.Context, userID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUserIDForUpdate, userID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.Avatar,
		&i.Role,
		&i.Status,
		&i.Token,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const getUserForUpdate = `-- name: GetUserForUpdate :one
SELECT id, first_name, last_name, email, password, phone, avatar, role, status, token, refresh_token, created_at, updated_at, user_id FROM users
WHERE id = $1 LIMIT 1
FOR UPDATE
`

func (q *Queries) GetUserForUpdate(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserForUpdate, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.Avatar,
		&i.Role,
		&i.Status,
		&i.Token,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, first_name, last_name, email, password, phone, avatar, role, status, token, refresh_token, created_at, updated_at, user_id FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Password,
			&i.Phone,
			&i.Avatar,
			&i.Role,
			&i.Status,
			&i.Token,
			&i.RefreshToken,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByRole = `-- name: ListUsersByRole :many
SELECT id, first_name, last_name, email, password, phone, avatar, role, status, token, refresh_token, created_at, updated_at, user_id FROM users
WHERE role = $1
ORDER BY created_at DESC
`

func (q *Queries) ListUsersByRole(ctx context.Context, role string) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsersByRole, role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Password,
			&i.Phone,
			&i.Avatar,
			&i.Role,
			&i.Status,
			&i.Token,
			&i.RefreshToken,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET 
    first_name = COALESCE($2, first_name),
    last_name = COALESCE($3, last_name),
    email = COALESCE($4, email),
    phone = COALESCE($5, phone),
    avatar = COALESCE($6, avatar),
    status = COALESCE($7, status),
    updated_at = now()
WHERE id = $1
RETURNING id, first_name, last_name, email, password, phone, avatar, role, status, token, refresh_token, created_at, updated_at, user_id
`

type UpdateUserParams struct {
	ID        uuid.UUID      `json:"id"`
	FirstName string         `json:"first_name"`
	LastName  string         `json:"last_name"`
	Email     string         `json:"email"`
	Phone     string         `json:"phone"`
	Avatar    sql.NullString `json:"avatar"`
	Status    string         `json:"status"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.Avatar,
		arg.Status,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.Avatar,
		&i.Role,
		&i.Status,
		&i.Token,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET 
    password = $2,
    updated_at = now()
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID       uuid.UUID `json:"id"`
	Password string    `json:"password"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.ID, arg.Password)
	return err
}

const updateUserTokens = `-- name: UpdateUserTokens :exec
UPDATE users
SET 
    token = $2,
    refresh_token = $3,
    updated_at = now()
WHERE id = $1
`

type UpdateUserTokensParams struct {
	ID           uuid.UUID      `json:"id"`
	Token        sql.NullString `json:"token"`
	RefreshToken sql.NullString `json:"refresh_token"`
}

func (q *Queries) UpdateUserTokens(ctx context.Context, arg UpdateUserTokensParams) error {
	_, err := q.db.ExecContext(ctx, updateUserTokens, arg.ID, arg.Token, arg.RefreshToken)
	return err
}
