// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.30.2
// source: order_services.proto

package order

import (
	reflect "reflect"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_order_services_proto protoreflect.FileDescriptor

const file_order_services_proto_rawDesc = "" +
	"\n" +
	"\x14order_services.proto\x12\x05order\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\vorder.proto2\xef\x01\n" +
	"\fOrderService\x12/\n" +
	"\rCreatePackage\x12\x0e.order.Package\x1a\x0e.order.Package\x12;\n" +
	"\x0eGetPackageById\x12\x0e.order.Package\x1a\x19.order.PackageFullDetails\x12:\n" +
	"\fListPackages\x12\x18.order.PaginationRequest\x1a\x0e.order.Package0\x01\x125\n" +
	"\x13UpdatePackageStatus\x12\x0e.order.Package\x1a\x0e.order.Package2\x81\x02\n" +
	"\x0fDeliveryService\x122\n" +
	"\x0eAssignDelivery\x12\x0f.order.Delivery\x1a\x0f.order.Delivery\x128\n" +
	"\x14UpdateDeliveryStatus\x12\x0f.order.Delivery\x1a\x0f.order.Delivery\x12A\n" +
	"\x12GetDeliveryDetails\x12\x0f.order.Delivery\x1a\x1a.order.DeliveryFullDetails\x12=\n" +
	"\x0eListDeliveries\x12\x18.order.PaginationRequest\x1a\x0f.order.Delivery0\x012\x8f\x01\n" +
	"\x0fTrackingService\x12>\n" +
	"\x10AddTrackingEvent\x12\x14.order.TrackingEvent\x1a\x14.order.TrackingEvent\x12<\n" +
	"\x12GetTrackingHistory\x12\x0e.order.Package\x1a\x14.order.TrackingEvent0\x012\xd4\x01\n" +
	"\fRouteService\x12)\n" +
	"\vCreateRoute\x12\f.order.Route\x1a\f.order.Route\x126\n" +
	"\x0fGetRouteDetails\x12\f.order.Route\x1a\x15.order.RouteWithStops\x12)\n" +
	"\vUpdateRoute\x12\f.order.Route\x1a\f.order.Route\x126\n" +
	"\n" +
	"ListRoutes\x12\x18.order.PaginationRequest\x1a\f.order.Route0\x01B\x1aZ\x18github.com/iambasill/streamfleet/pb/orderb\x06proto3"

var file_order_services_proto_goTypes = []any{
	(*Package)(nil),             // 0: order.Package
	(*PaginationRequest)(nil),   // 1: order.PaginationRequest
	(*Delivery)(nil),            // 2: order.Delivery
	(*TrackingEvent)(nil),       // 3: order.TrackingEvent
	(*Route)(nil),               // 4: order.Route
	(*PackageFullDetails)(nil),  // 5: order.PackageFullDetails
	(*DeliveryFullDetails)(nil), // 6: order.DeliveryFullDetails
	(*RouteWithStops)(nil),      // 7: order.RouteWithStops
}
var file_order_services_proto_depIdxs = []int32{
	0,  // 0: order.OrderService.CreatePackage:input_type -> order.Package
	0,  // 1: order.OrderService.GetPackageById:input_type -> order.Package
	1,  // 2: order.OrderService.ListPackages:input_type -> order.PaginationRequest
	0,  // 3: order.OrderService.UpdatePackageStatus:input_type -> order.Package
	2,  // 4: order.DeliveryService.AssignDelivery:input_type -> order.Delivery
	2,  // 5: order.DeliveryService.UpdateDeliveryStatus:input_type -> order.Delivery
	2,  // 6: order.DeliveryService.GetDeliveryDetails:input_type -> order.Delivery
	1,  // 7: order.DeliveryService.ListDeliveries:input_type -> order.PaginationRequest
	3,  // 8: order.TrackingService.AddTrackingEvent:input_type -> order.TrackingEvent
	0,  // 9: order.TrackingService.GetTrackingHistory:input_type -> order.Package
	4,  // 10: order.RouteService.CreateRoute:input_type -> order.Route
	4,  // 11: order.RouteService.GetRouteDetails:input_type -> order.Route
	4,  // 12: order.RouteService.UpdateRoute:input_type -> order.Route
	1,  // 13: order.RouteService.ListRoutes:input_type -> order.PaginationRequest
	0,  // 14: order.OrderService.CreatePackage:output_type -> order.Package
	5,  // 15: order.OrderService.GetPackageById:output_type -> order.PackageFullDetails
	0,  // 16: order.OrderService.ListPackages:output_type -> order.Package
	0,  // 17: order.OrderService.UpdatePackageStatus:output_type -> order.Package
	2,  // 18: order.DeliveryService.AssignDelivery:output_type -> order.Delivery
	2,  // 19: order.DeliveryService.UpdateDeliveryStatus:output_type -> order.Delivery
	6,  // 20: order.DeliveryService.GetDeliveryDetails:output_type -> order.DeliveryFullDetails
	2,  // 21: order.DeliveryService.ListDeliveries:output_type -> order.Delivery
	3,  // 22: order.TrackingService.AddTrackingEvent:output_type -> order.TrackingEvent
	3,  // 23: order.TrackingService.GetTrackingHistory:output_type -> order.TrackingEvent
	4,  // 24: order.RouteService.CreateRoute:output_type -> order.Route
	7,  // 25: order.RouteService.GetRouteDetails:output_type -> order.RouteWithStops
	4,  // 26: order.RouteService.UpdateRoute:output_type -> order.Route
	4,  // 27: order.RouteService.ListRoutes:output_type -> order.Route
	14, // [14:28] is the sub-list for method output_type
	0,  // [0:14] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_order_services_proto_init() }
func file_order_services_proto_init() {
	if File_order_services_proto != nil {
		return
	}
	file_order_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_services_proto_rawDesc), len(file_order_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_order_services_proto_goTypes,
		DependencyIndexes: file_order_services_proto_depIdxs,
	}.Build()
	File_order_services_proto = out.File
	file_order_services_proto_goTypes = nil
	file_order_services_proto_depIdxs = nil
}
