// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: order_services.proto

package order

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderService_CreatePackage_FullMethodName       = "/order.OrderService/CreatePackage"
	OrderService_GetPackageById_FullMethodName      = "/order.OrderService/GetPackageById"
	OrderService_ListPackages_FullMethodName        = "/order.OrderService/ListPackages"
	OrderService_UpdatePackageStatus_FullMethodName = "/order.OrderService/UpdatePackageStatus"
)

// OrderServiceClient is the client API for OrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderServiceClient interface {
	CreatePackage(ctx context.Context, in *Package, opts ...grpc.CallOption) (*Package, error)
	GetPackageById(ctx context.Context, in *Package, opts ...grpc.CallOption) (*PackageFullDetails, error)
	ListPackages(ctx context.Context, in *PaginationRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Package], error)
	UpdatePackageStatus(ctx context.Context, in *Package, opts ...grpc.CallOption) (*Package, error)
}

type orderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderServiceClient(cc grpc.ClientConnInterface) OrderServiceClient {
	return &orderServiceClient{cc}
}

func (c *orderServiceClient) CreatePackage(ctx context.Context, in *Package, opts ...grpc.CallOption) (*Package, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Package)
	err := c.cc.Invoke(ctx, OrderService_CreatePackage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetPackageById(ctx context.Context, in *Package, opts ...grpc.CallOption) (*PackageFullDetails, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PackageFullDetails)
	err := c.cc.Invoke(ctx, OrderService_GetPackageById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) ListPackages(ctx context.Context, in *PaginationRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Package], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OrderService_ServiceDesc.Streams[0], OrderService_ListPackages_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PaginationRequest, Package]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrderService_ListPackagesClient = grpc.ServerStreamingClient[Package]

func (c *orderServiceClient) UpdatePackageStatus(ctx context.Context, in *Package, opts ...grpc.CallOption) (*Package, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Package)
	err := c.cc.Invoke(ctx, OrderService_UpdatePackageStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServiceServer is the server API for OrderService service.
// All implementations must embed UnimplementedOrderServiceServer
// for forward compatibility.
type OrderServiceServer interface {
	CreatePackage(context.Context, *Package) (*Package, error)
	GetPackageById(context.Context, *Package) (*PackageFullDetails, error)
	ListPackages(*PaginationRequest, grpc.ServerStreamingServer[Package]) error
	UpdatePackageStatus(context.Context, *Package) (*Package, error)
	mustEmbedUnimplementedOrderServiceServer()
}

// UnimplementedOrderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderServiceServer struct{}

func (UnimplementedOrderServiceServer) CreatePackage(context.Context, *Package) (*Package, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePackage not implemented")
}
func (UnimplementedOrderServiceServer) GetPackageById(context.Context, *Package) (*PackageFullDetails, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPackageById not implemented")
}
func (UnimplementedOrderServiceServer) ListPackages(*PaginationRequest, grpc.ServerStreamingServer[Package]) error {
	return status.Errorf(codes.Unimplemented, "method ListPackages not implemented")
}
func (UnimplementedOrderServiceServer) UpdatePackageStatus(context.Context, *Package) (*Package, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePackageStatus not implemented")
}
func (UnimplementedOrderServiceServer) mustEmbedUnimplementedOrderServiceServer() {}
func (UnimplementedOrderServiceServer) testEmbeddedByValue()                      {}

// UnsafeOrderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderServiceServer will
// result in compilation errors.
type UnsafeOrderServiceServer interface {
	mustEmbedUnimplementedOrderServiceServer()
}

func RegisterOrderServiceServer(s grpc.ServiceRegistrar, srv OrderServiceServer) {
	// If the following call pancis, it indicates UnimplementedOrderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderService_ServiceDesc, srv)
}

func _OrderService_CreatePackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Package)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).CreatePackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_CreatePackage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).CreatePackage(ctx, req.(*Package))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetPackageById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Package)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetPackageById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_GetPackageById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetPackageById(ctx, req.(*Package))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_ListPackages_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PaginationRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrderServiceServer).ListPackages(m, &grpc.GenericServerStream[PaginationRequest, Package]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrderService_ListPackagesServer = grpc.ServerStreamingServer[Package]

func _OrderService_UpdatePackageStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Package)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).UpdatePackageStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_UpdatePackageStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).UpdatePackageStatus(ctx, req.(*Package))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderService_ServiceDesc is the grpc.ServiceDesc for OrderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order.OrderService",
	HandlerType: (*OrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePackage",
			Handler:    _OrderService_CreatePackage_Handler,
		},
		{
			MethodName: "GetPackageById",
			Handler:    _OrderService_GetPackageById_Handler,
		},
		{
			MethodName: "UpdatePackageStatus",
			Handler:    _OrderService_UpdatePackageStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListPackages",
			Handler:       _OrderService_ListPackages_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "order_services.proto",
}

const (
	DeliveryService_AssignDelivery_FullMethodName       = "/order.DeliveryService/AssignDelivery"
	DeliveryService_UpdateDeliveryStatus_FullMethodName = "/order.DeliveryService/UpdateDeliveryStatus"
	DeliveryService_GetDeliveryDetails_FullMethodName   = "/order.DeliveryService/GetDeliveryDetails"
	DeliveryService_ListDeliveries_FullMethodName       = "/order.DeliveryService/ListDeliveries"
)

// DeliveryServiceClient is the client API for DeliveryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeliveryServiceClient interface {
	AssignDelivery(ctx context.Context, in *Delivery, opts ...grpc.CallOption) (*Delivery, error)
	UpdateDeliveryStatus(ctx context.Context, in *Delivery, opts ...grpc.CallOption) (*Delivery, error)
	GetDeliveryDetails(ctx context.Context, in *Delivery, opts ...grpc.CallOption) (*DeliveryFullDetails, error)
	ListDeliveries(ctx context.Context, in *PaginationRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Delivery], error)
}

type deliveryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeliveryServiceClient(cc grpc.ClientConnInterface) DeliveryServiceClient {
	return &deliveryServiceClient{cc}
}

func (c *deliveryServiceClient) AssignDelivery(ctx context.Context, in *Delivery, opts ...grpc.CallOption) (*Delivery, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Delivery)
	err := c.cc.Invoke(ctx, DeliveryService_AssignDelivery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryServiceClient) UpdateDeliveryStatus(ctx context.Context, in *Delivery, opts ...grpc.CallOption) (*Delivery, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Delivery)
	err := c.cc.Invoke(ctx, DeliveryService_UpdateDeliveryStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryServiceClient) GetDeliveryDetails(ctx context.Context, in *Delivery, opts ...grpc.CallOption) (*DeliveryFullDetails, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliveryFullDetails)
	err := c.cc.Invoke(ctx, DeliveryService_GetDeliveryDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryServiceClient) ListDeliveries(ctx context.Context, in *PaginationRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Delivery], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DeliveryService_ServiceDesc.Streams[0], DeliveryService_ListDeliveries_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PaginationRequest, Delivery]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeliveryService_ListDeliveriesClient = grpc.ServerStreamingClient[Delivery]

// DeliveryServiceServer is the server API for DeliveryService service.
// All implementations must embed UnimplementedDeliveryServiceServer
// for forward compatibility.
type DeliveryServiceServer interface {
	AssignDelivery(context.Context, *Delivery) (*Delivery, error)
	UpdateDeliveryStatus(context.Context, *Delivery) (*Delivery, error)
	GetDeliveryDetails(context.Context, *Delivery) (*DeliveryFullDetails, error)
	ListDeliveries(*PaginationRequest, grpc.ServerStreamingServer[Delivery]) error
	mustEmbedUnimplementedDeliveryServiceServer()
}

// UnimplementedDeliveryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeliveryServiceServer struct{}

func (UnimplementedDeliveryServiceServer) AssignDelivery(context.Context, *Delivery) (*Delivery, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssignDelivery not implemented")
}
func (UnimplementedDeliveryServiceServer) UpdateDeliveryStatus(context.Context, *Delivery) (*Delivery, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDeliveryStatus not implemented")
}
func (UnimplementedDeliveryServiceServer) GetDeliveryDetails(context.Context, *Delivery) (*DeliveryFullDetails, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeliveryDetails not implemented")
}
func (UnimplementedDeliveryServiceServer) ListDeliveries(*PaginationRequest, grpc.ServerStreamingServer[Delivery]) error {
	return status.Errorf(codes.Unimplemented, "method ListDeliveries not implemented")
}
func (UnimplementedDeliveryServiceServer) mustEmbedUnimplementedDeliveryServiceServer() {}
func (UnimplementedDeliveryServiceServer) testEmbeddedByValue()                         {}

// UnsafeDeliveryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeliveryServiceServer will
// result in compilation errors.
type UnsafeDeliveryServiceServer interface {
	mustEmbedUnimplementedDeliveryServiceServer()
}

func RegisterDeliveryServiceServer(s grpc.ServiceRegistrar, srv DeliveryServiceServer) {
	// If the following call pancis, it indicates UnimplementedDeliveryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeliveryService_ServiceDesc, srv)
}

func _DeliveryService_AssignDelivery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Delivery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).AssignDelivery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_AssignDelivery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).AssignDelivery(ctx, req.(*Delivery))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryService_UpdateDeliveryStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Delivery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).UpdateDeliveryStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_UpdateDeliveryStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).UpdateDeliveryStatus(ctx, req.(*Delivery))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryService_GetDeliveryDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Delivery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).GetDeliveryDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_GetDeliveryDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).GetDeliveryDetails(ctx, req.(*Delivery))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryService_ListDeliveries_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PaginationRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DeliveryServiceServer).ListDeliveries(m, &grpc.GenericServerStream[PaginationRequest, Delivery]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeliveryService_ListDeliveriesServer = grpc.ServerStreamingServer[Delivery]

// DeliveryService_ServiceDesc is the grpc.ServiceDesc for DeliveryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeliveryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order.DeliveryService",
	HandlerType: (*DeliveryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AssignDelivery",
			Handler:    _DeliveryService_AssignDelivery_Handler,
		},
		{
			MethodName: "UpdateDeliveryStatus",
			Handler:    _DeliveryService_UpdateDeliveryStatus_Handler,
		},
		{
			MethodName: "GetDeliveryDetails",
			Handler:    _DeliveryService_GetDeliveryDetails_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListDeliveries",
			Handler:       _DeliveryService_ListDeliveries_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "order_services.proto",
}

const (
	TrackingService_AddTrackingEvent_FullMethodName   = "/order.TrackingService/AddTrackingEvent"
	TrackingService_GetTrackingHistory_FullMethodName = "/order.TrackingService/GetTrackingHistory"
)

// TrackingServiceClient is the client API for TrackingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrackingServiceClient interface {
	AddTrackingEvent(ctx context.Context, in *TrackingEvent, opts ...grpc.CallOption) (*TrackingEvent, error)
	GetTrackingHistory(ctx context.Context, in *Package, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TrackingEvent], error)
}

type trackingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrackingServiceClient(cc grpc.ClientConnInterface) TrackingServiceClient {
	return &trackingServiceClient{cc}
}

func (c *trackingServiceClient) AddTrackingEvent(ctx context.Context, in *TrackingEvent, opts ...grpc.CallOption) (*TrackingEvent, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrackingEvent)
	err := c.cc.Invoke(ctx, TrackingService_AddTrackingEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackingServiceClient) GetTrackingHistory(ctx context.Context, in *Package, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TrackingEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TrackingService_ServiceDesc.Streams[0], TrackingService_GetTrackingHistory_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Package, TrackingEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TrackingService_GetTrackingHistoryClient = grpc.ServerStreamingClient[TrackingEvent]

// TrackingServiceServer is the server API for TrackingService service.
// All implementations must embed UnimplementedTrackingServiceServer
// for forward compatibility.
type TrackingServiceServer interface {
	AddTrackingEvent(context.Context, *TrackingEvent) (*TrackingEvent, error)
	GetTrackingHistory(*Package, grpc.ServerStreamingServer[TrackingEvent]) error
	mustEmbedUnimplementedTrackingServiceServer()
}

// UnimplementedTrackingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrackingServiceServer struct{}

func (UnimplementedTrackingServiceServer) AddTrackingEvent(context.Context, *TrackingEvent) (*TrackingEvent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTrackingEvent not implemented")
}
func (UnimplementedTrackingServiceServer) GetTrackingHistory(*Package, grpc.ServerStreamingServer[TrackingEvent]) error {
	return status.Errorf(codes.Unimplemented, "method GetTrackingHistory not implemented")
}
func (UnimplementedTrackingServiceServer) mustEmbedUnimplementedTrackingServiceServer() {}
func (UnimplementedTrackingServiceServer) testEmbeddedByValue()                         {}

// UnsafeTrackingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrackingServiceServer will
// result in compilation errors.
type UnsafeTrackingServiceServer interface {
	mustEmbedUnimplementedTrackingServiceServer()
}

func RegisterTrackingServiceServer(s grpc.ServiceRegistrar, srv TrackingServiceServer) {
	// If the following call pancis, it indicates UnimplementedTrackingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TrackingService_ServiceDesc, srv)
}

func _TrackingService_AddTrackingEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrackingEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackingServiceServer).AddTrackingEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackingService_AddTrackingEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackingServiceServer).AddTrackingEvent(ctx, req.(*TrackingEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrackingService_GetTrackingHistory_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Package)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TrackingServiceServer).GetTrackingHistory(m, &grpc.GenericServerStream[Package, TrackingEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TrackingService_GetTrackingHistoryServer = grpc.ServerStreamingServer[TrackingEvent]

// TrackingService_ServiceDesc is the grpc.ServiceDesc for TrackingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrackingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order.TrackingService",
	HandlerType: (*TrackingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddTrackingEvent",
			Handler:    _TrackingService_AddTrackingEvent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetTrackingHistory",
			Handler:       _TrackingService_GetTrackingHistory_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "order_services.proto",
}

const (
	RouteService_CreateRoute_FullMethodName     = "/order.RouteService/CreateRoute"
	RouteService_GetRouteDetails_FullMethodName = "/order.RouteService/GetRouteDetails"
	RouteService_UpdateRoute_FullMethodName     = "/order.RouteService/UpdateRoute"
	RouteService_ListRoutes_FullMethodName      = "/order.RouteService/ListRoutes"
)

// RouteServiceClient is the client API for RouteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RouteServiceClient interface {
	CreateRoute(ctx context.Context, in *Route, opts ...grpc.CallOption) (*Route, error)
	GetRouteDetails(ctx context.Context, in *Route, opts ...grpc.CallOption) (*RouteWithStops, error)
	UpdateRoute(ctx context.Context, in *Route, opts ...grpc.CallOption) (*Route, error)
	ListRoutes(ctx context.Context, in *PaginationRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Route], error)
}

type routeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRouteServiceClient(cc grpc.ClientConnInterface) RouteServiceClient {
	return &routeServiceClient{cc}
}

func (c *routeServiceClient) CreateRoute(ctx context.Context, in *Route, opts ...grpc.CallOption) (*Route, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Route)
	err := c.cc.Invoke(ctx, RouteService_CreateRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeServiceClient) GetRouteDetails(ctx context.Context, in *Route, opts ...grpc.CallOption) (*RouteWithStops, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RouteWithStops)
	err := c.cc.Invoke(ctx, RouteService_GetRouteDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeServiceClient) UpdateRoute(ctx context.Context, in *Route, opts ...grpc.CallOption) (*Route, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Route)
	err := c.cc.Invoke(ctx, RouteService_UpdateRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeServiceClient) ListRoutes(ctx context.Context, in *PaginationRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Route], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RouteService_ServiceDesc.Streams[0], RouteService_ListRoutes_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PaginationRequest, Route]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RouteService_ListRoutesClient = grpc.ServerStreamingClient[Route]

// RouteServiceServer is the server API for RouteService service.
// All implementations must embed UnimplementedRouteServiceServer
// for forward compatibility.
type RouteServiceServer interface {
	CreateRoute(context.Context, *Route) (*Route, error)
	GetRouteDetails(context.Context, *Route) (*RouteWithStops, error)
	UpdateRoute(context.Context, *Route) (*Route, error)
	ListRoutes(*PaginationRequest, grpc.ServerStreamingServer[Route]) error
	mustEmbedUnimplementedRouteServiceServer()
}

// UnimplementedRouteServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRouteServiceServer struct{}

func (UnimplementedRouteServiceServer) CreateRoute(context.Context, *Route) (*Route, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRoute not implemented")
}
func (UnimplementedRouteServiceServer) GetRouteDetails(context.Context, *Route) (*RouteWithStops, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRouteDetails not implemented")
}
func (UnimplementedRouteServiceServer) UpdateRoute(context.Context, *Route) (*Route, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRoute not implemented")
}
func (UnimplementedRouteServiceServer) ListRoutes(*PaginationRequest, grpc.ServerStreamingServer[Route]) error {
	return status.Errorf(codes.Unimplemented, "method ListRoutes not implemented")
}
func (UnimplementedRouteServiceServer) mustEmbedUnimplementedRouteServiceServer() {}
func (UnimplementedRouteServiceServer) testEmbeddedByValue()                      {}

// UnsafeRouteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RouteServiceServer will
// result in compilation errors.
type UnsafeRouteServiceServer interface {
	mustEmbedUnimplementedRouteServiceServer()
}

func RegisterRouteServiceServer(s grpc.ServiceRegistrar, srv RouteServiceServer) {
	// If the following call pancis, it indicates UnimplementedRouteServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RouteService_ServiceDesc, srv)
}

func _RouteService_CreateRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Route)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteServiceServer).CreateRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteService_CreateRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteServiceServer).CreateRoute(ctx, req.(*Route))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteService_GetRouteDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Route)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteServiceServer).GetRouteDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteService_GetRouteDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteServiceServer).GetRouteDetails(ctx, req.(*Route))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteService_UpdateRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Route)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteServiceServer).UpdateRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteService_UpdateRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteServiceServer).UpdateRoute(ctx, req.(*Route))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteService_ListRoutes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PaginationRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RouteServiceServer).ListRoutes(m, &grpc.GenericServerStream[PaginationRequest, Route]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RouteService_ListRoutesServer = grpc.ServerStreamingServer[Route]

// RouteService_ServiceDesc is the grpc.ServiceDesc for RouteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RouteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order.RouteService",
	HandlerType: (*RouteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRoute",
			Handler:    _RouteService_CreateRoute_Handler,
		},
		{
			MethodName: "GetRouteDetails",
			Handler:    _RouteService_GetRouteDetails_Handler,
		},
		{
			MethodName: "UpdateRoute",
			Handler:    _RouteService_UpdateRoute_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListRoutes",
			Handler:       _RouteService_ListRoutes_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "order_services.proto",
}
