// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.30.2
// source: order.proto

package order

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PackageStatus int32

const (
	PackageStatus_PACKAGE_STATUS_UNSPECIFIED      PackageStatus = 0
	PackageStatus_PACKAGE_STATUS_PENDING          PackageStatus = 1
	PackageStatus_PACKAGE_STATUS_PICKED_UP        PackageStatus = 2
	PackageStatus_PACKAGE_STATUS_IN_TRANSIT       PackageStatus = 3
	PackageStatus_PACKAGE_STATUS_OUT_FOR_DELIVERY PackageStatus = 4
	PackageStatus_PACKAGE_STATUS_DELIVERED        PackageStatus = 5
	PackageStatus_PACKAGE_STATUS_FAILED           PackageStatus = 6
	PackageStatus_PACKAGE_STATUS_CANCELLED        PackageStatus = 7
)

// Enum value maps for PackageStatus.
var (
	PackageStatus_name = map[int32]string{
		0: "PACKAGE_STATUS_UNSPECIFIED",
		1: "PACKAGE_STATUS_PENDING",
		2: "PACKAGE_STATUS_PICKED_UP",
		3: "PACKAGE_STATUS_IN_TRANSIT",
		4: "PACKAGE_STATUS_OUT_FOR_DELIVERY",
		5: "PACKAGE_STATUS_DELIVERED",
		6: "PACKAGE_STATUS_FAILED",
		7: "PACKAGE_STATUS_CANCELLED",
	}
	PackageStatus_value = map[string]int32{
		"PACKAGE_STATUS_UNSPECIFIED":      0,
		"PACKAGE_STATUS_PENDING":          1,
		"PACKAGE_STATUS_PICKED_UP":        2,
		"PACKAGE_STATUS_IN_TRANSIT":       3,
		"PACKAGE_STATUS_OUT_FOR_DELIVERY": 4,
		"PACKAGE_STATUS_DELIVERED":        5,
		"PACKAGE_STATUS_FAILED":           6,
		"PACKAGE_STATUS_CANCELLED":        7,
	}
)

func (x PackageStatus) Enum() *PackageStatus {
	p := new(PackageStatus)
	*p = x
	return p
}

func (x PackageStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PackageStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_order_proto_enumTypes[0].Descriptor()
}

func (PackageStatus) Type() protoreflect.EnumType {
	return &file_order_proto_enumTypes[0]
}

func (x PackageStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PackageStatus.Descriptor instead.
func (PackageStatus) EnumDescriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

type PackagePriority int32

const (
	PackagePriority_PACKAGE_PRIORITY_UNSPECIFIED PackagePriority = 0
	PackagePriority_PACKAGE_PRIORITY_ECONOMY     PackagePriority = 1
	PackagePriority_PACKAGE_PRIORITY_STANDARD    PackagePriority = 2
	PackagePriority_PACKAGE_PRIORITY_EXPRESS     PackagePriority = 3
)

// Enum value maps for PackagePriority.
var (
	PackagePriority_name = map[int32]string{
		0: "PACKAGE_PRIORITY_UNSPECIFIED",
		1: "PACKAGE_PRIORITY_ECONOMY",
		2: "PACKAGE_PRIORITY_STANDARD",
		3: "PACKAGE_PRIORITY_EXPRESS",
	}
	PackagePriority_value = map[string]int32{
		"PACKAGE_PRIORITY_UNSPECIFIED": 0,
		"PACKAGE_PRIORITY_ECONOMY":     1,
		"PACKAGE_PRIORITY_STANDARD":    2,
		"PACKAGE_PRIORITY_EXPRESS":     3,
	}
)

func (x PackagePriority) Enum() *PackagePriority {
	p := new(PackagePriority)
	*p = x
	return p
}

func (x PackagePriority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PackagePriority) Descriptor() protoreflect.EnumDescriptor {
	return file_order_proto_enumTypes[1].Descriptor()
}

func (PackagePriority) Type() protoreflect.EnumType {
	return &file_order_proto_enumTypes[1]
}

func (x PackagePriority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PackagePriority.Descriptor instead.
func (PackagePriority) EnumDescriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

type PackageCategory int32

const (
	PackageCategory_PACKAGE_CATEGORY_UNSPECIFIED PackageCategory = 0
	PackageCategory_PACKAGE_CATEGORY_DOCUMENTS   PackageCategory = 1
	PackageCategory_PACKAGE_CATEGORY_ELECTRONICS PackageCategory = 2
	PackageCategory_PACKAGE_CATEGORY_FOOD        PackageCategory = 3
	PackageCategory_PACKAGE_CATEGORY_FRAGILE     PackageCategory = 4
	PackageCategory_PACKAGE_CATEGORY_CLOTHING    PackageCategory = 5
	PackageCategory_PACKAGE_CATEGORY_GENERAL     PackageCategory = 6
)

// Enum value maps for PackageCategory.
var (
	PackageCategory_name = map[int32]string{
		0: "PACKAGE_CATEGORY_UNSPECIFIED",
		1: "PACKAGE_CATEGORY_DOCUMENTS",
		2: "PACKAGE_CATEGORY_ELECTRONICS",
		3: "PACKAGE_CATEGORY_FOOD",
		4: "PACKAGE_CATEGORY_FRAGILE",
		5: "PACKAGE_CATEGORY_CLOTHING",
		6: "PACKAGE_CATEGORY_GENERAL",
	}
	PackageCategory_value = map[string]int32{
		"PACKAGE_CATEGORY_UNSPECIFIED": 0,
		"PACKAGE_CATEGORY_DOCUMENTS":   1,
		"PACKAGE_CATEGORY_ELECTRONICS": 2,
		"PACKAGE_CATEGORY_FOOD":        3,
		"PACKAGE_CATEGORY_FRAGILE":     4,
		"PACKAGE_CATEGORY_CLOTHING":    5,
		"PACKAGE_CATEGORY_GENERAL":     6,
	}
)

func (x PackageCategory) Enum() *PackageCategory {
	p := new(PackageCategory)
	*p = x
	return p
}

func (x PackageCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PackageCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_order_proto_enumTypes[2].Descriptor()
}

func (PackageCategory) Type() protoreflect.EnumType {
	return &file_order_proto_enumTypes[2]
}

func (x PackageCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PackageCategory.Descriptor instead.
func (PackageCategory) EnumDescriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2}
}

type DeliveryStatus int32

const (
	DeliveryStatus_DELIVERY_STATUS_UNSPECIFIED DeliveryStatus = 0
	DeliveryStatus_DELIVERY_STATUS_ASSIGNED    DeliveryStatus = 1
	DeliveryStatus_DELIVERY_STATUS_IN_PROGRESS DeliveryStatus = 2
	DeliveryStatus_DELIVERY_STATUS_COMPLETED   DeliveryStatus = 3
	DeliveryStatus_DELIVERY_STATUS_FAILED      DeliveryStatus = 4
	DeliveryStatus_DELIVERY_STATUS_CANCELLED   DeliveryStatus = 5
)

// Enum value maps for DeliveryStatus.
var (
	DeliveryStatus_name = map[int32]string{
		0: "DELIVERY_STATUS_UNSPECIFIED",
		1: "DELIVERY_STATUS_ASSIGNED",
		2: "DELIVERY_STATUS_IN_PROGRESS",
		3: "DELIVERY_STATUS_COMPLETED",
		4: "DELIVERY_STATUS_FAILED",
		5: "DELIVERY_STATUS_CANCELLED",
	}
	DeliveryStatus_value = map[string]int32{
		"DELIVERY_STATUS_UNSPECIFIED": 0,
		"DELIVERY_STATUS_ASSIGNED":    1,
		"DELIVERY_STATUS_IN_PROGRESS": 2,
		"DELIVERY_STATUS_COMPLETED":   3,
		"DELIVERY_STATUS_FAILED":      4,
		"DELIVERY_STATUS_CANCELLED":   5,
	}
)

func (x DeliveryStatus) Enum() *DeliveryStatus {
	p := new(DeliveryStatus)
	*p = x
	return p
}

func (x DeliveryStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeliveryStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_order_proto_enumTypes[3].Descriptor()
}

func (DeliveryStatus) Type() protoreflect.EnumType {
	return &file_order_proto_enumTypes[3]
}

func (x DeliveryStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeliveryStatus.Descriptor instead.
func (DeliveryStatus) EnumDescriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{3}
}

type TrackingEventType int32

const (
	TrackingEventType_TRACKING_EVENT_TYPE_UNSPECIFIED      TrackingEventType = 0
	TrackingEventType_TRACKING_EVENT_TYPE_CREATED          TrackingEventType = 1
	TrackingEventType_TRACKING_EVENT_TYPE_ASSIGNED         TrackingEventType = 2
	TrackingEventType_TRACKING_EVENT_TYPE_PICKED_UP        TrackingEventType = 3
	TrackingEventType_TRACKING_EVENT_TYPE_IN_TRANSIT       TrackingEventType = 4
	TrackingEventType_TRACKING_EVENT_TYPE_OUT_FOR_DELIVERY TrackingEventType = 5
	TrackingEventType_TRACKING_EVENT_TYPE_DELIVERED        TrackingEventType = 6
	TrackingEventType_TRACKING_EVENT_TYPE_EXCEPTION        TrackingEventType = 7
	TrackingEventType_TRACKING_EVENT_TYPE_CANCELLED        TrackingEventType = 8
)

// Enum value maps for TrackingEventType.
var (
	TrackingEventType_name = map[int32]string{
		0: "TRACKING_EVENT_TYPE_UNSPECIFIED",
		1: "TRACKING_EVENT_TYPE_CREATED",
		2: "TRACKING_EVENT_TYPE_ASSIGNED",
		3: "TRACKING_EVENT_TYPE_PICKED_UP",
		4: "TRACKING_EVENT_TYPE_IN_TRANSIT",
		5: "TRACKING_EVENT_TYPE_OUT_FOR_DELIVERY",
		6: "TRACKING_EVENT_TYPE_DELIVERED",
		7: "TRACKING_EVENT_TYPE_EXCEPTION",
		8: "TRACKING_EVENT_TYPE_CANCELLED",
	}
	TrackingEventType_value = map[string]int32{
		"TRACKING_EVENT_TYPE_UNSPECIFIED":      0,
		"TRACKING_EVENT_TYPE_CREATED":          1,
		"TRACKING_EVENT_TYPE_ASSIGNED":         2,
		"TRACKING_EVENT_TYPE_PICKED_UP":        3,
		"TRACKING_EVENT_TYPE_IN_TRANSIT":       4,
		"TRACKING_EVENT_TYPE_OUT_FOR_DELIVERY": 5,
		"TRACKING_EVENT_TYPE_DELIVERED":        6,
		"TRACKING_EVENT_TYPE_EXCEPTION":        7,
		"TRACKING_EVENT_TYPE_CANCELLED":        8,
	}
)

func (x TrackingEventType) Enum() *TrackingEventType {
	p := new(TrackingEventType)
	*p = x
	return p
}

func (x TrackingEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TrackingEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_order_proto_enumTypes[4].Descriptor()
}

func (TrackingEventType) Type() protoreflect.EnumType {
	return &file_order_proto_enumTypes[4]
}

func (x TrackingEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TrackingEventType.Descriptor instead.
func (TrackingEventType) EnumDescriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{4}
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AddressId     string                 `protobuf:"bytes,2,opt,name=address_id,json=addressId,proto3" json:"address_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Label         string                 `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	StreetAddress string                 `protobuf:"bytes,5,opt,name=street_address,json=streetAddress,proto3" json:"street_address,omitempty"`
	City          string                 `protobuf:"bytes,6,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,7,opt,name=state,proto3" json:"state,omitempty"`
	PostalCode    string                 `protobuf:"bytes,8,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Country       string                 `protobuf:"bytes,9,opt,name=country,proto3" json:"country,omitempty"`
	Latitude      float64                `protobuf:"fixed64,10,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,11,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Instructions  string                 `protobuf:"bytes,12,opt,name=instructions,proto3" json:"instructions,omitempty"`
	IsDefault     bool                   `protobuf:"varint,13,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Address) GetAddressId() string {
	if x != nil {
		return x.AddressId
	}
	return ""
}

func (x *Address) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Address) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Address) GetStreetAddress() string {
	if x != nil {
		return x.StreetAddress
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Address) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Address) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Address) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Address) GetInstructions() string {
	if x != nil {
		return x.Instructions
	}
	return ""
}

func (x *Address) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *Address) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Address) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Package struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PackageId         string                 `protobuf:"bytes,2,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	CustomerId        string                 `protobuf:"bytes,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	TrackingNumber    string                 `protobuf:"bytes,4,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	Description       string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Weight            float64                `protobuf:"fixed64,6,opt,name=weight,proto3" json:"weight,omitempty"`
	Dimensions        string                 `protobuf:"bytes,7,opt,name=dimensions,proto3" json:"dimensions,omitempty"`
	Category          PackageCategory        `protobuf:"varint,8,opt,name=category,proto3,enum=order.PackageCategory" json:"category,omitempty"`
	Value             float64                `protobuf:"fixed64,9,opt,name=value,proto3" json:"value,omitempty"`
	Priority          PackagePriority        `protobuf:"varint,10,opt,name=priority,proto3,enum=order.PackagePriority" json:"priority,omitempty"`
	SpecialHandling   string                 `protobuf:"bytes,11,opt,name=special_handling,json=specialHandling,proto3" json:"special_handling,omitempty"`
	PickupAddressId   string                 `protobuf:"bytes,12,opt,name=pickup_address_id,json=pickupAddressId,proto3" json:"pickup_address_id,omitempty"`
	DeliveryAddressId string                 `protobuf:"bytes,13,opt,name=delivery_address_id,json=deliveryAddressId,proto3" json:"delivery_address_id,omitempty"`
	Status            PackageStatus          `protobuf:"varint,14,opt,name=status,proto3,enum=order.PackageStatus" json:"status,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Package) Reset() {
	*x = Package{}
	mi := &file_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Package) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Package) ProtoMessage() {}

func (x *Package) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Package.ProtoReflect.Descriptor instead.
func (*Package) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

func (x *Package) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Package) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *Package) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *Package) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

func (x *Package) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Package) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Package) GetDimensions() string {
	if x != nil {
		return x.Dimensions
	}
	return ""
}

func (x *Package) GetCategory() PackageCategory {
	if x != nil {
		return x.Category
	}
	return PackageCategory_PACKAGE_CATEGORY_UNSPECIFIED
}

func (x *Package) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Package) GetPriority() PackagePriority {
	if x != nil {
		return x.Priority
	}
	return PackagePriority_PACKAGE_PRIORITY_UNSPECIFIED
}

func (x *Package) GetSpecialHandling() string {
	if x != nil {
		return x.SpecialHandling
	}
	return ""
}

func (x *Package) GetPickupAddressId() string {
	if x != nil {
		return x.PickupAddressId
	}
	return ""
}

func (x *Package) GetDeliveryAddressId() string {
	if x != nil {
		return x.DeliveryAddressId
	}
	return ""
}

func (x *Package) GetStatus() PackageStatus {
	if x != nil {
		return x.Status
	}
	return PackageStatus_PACKAGE_STATUS_UNSPECIFIED
}

func (x *Package) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Package) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type PackageWithAddresses struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Package         *Package               `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	PickupAddress   *Address               `protobuf:"bytes,2,opt,name=pickup_address,json=pickupAddress,proto3" json:"pickup_address,omitempty"`
	DeliveryAddress *Address               `protobuf:"bytes,3,opt,name=delivery_address,json=deliveryAddress,proto3" json:"delivery_address,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PackageWithAddresses) Reset() {
	*x = PackageWithAddresses{}
	mi := &file_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageWithAddresses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageWithAddresses) ProtoMessage() {}

func (x *PackageWithAddresses) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageWithAddresses.ProtoReflect.Descriptor instead.
func (*PackageWithAddresses) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2}
}

func (x *PackageWithAddresses) GetPackage() *Package {
	if x != nil {
		return x.Package
	}
	return nil
}

func (x *PackageWithAddresses) GetPickupAddress() *Address {
	if x != nil {
		return x.PickupAddress
	}
	return nil
}

func (x *PackageWithAddresses) GetDeliveryAddress() *Address {
	if x != nil {
		return x.DeliveryAddress
	}
	return nil
}

type PackageFullDetails struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Package         *Package               `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	PickupAddress   *Address               `protobuf:"bytes,2,opt,name=pickup_address,json=pickupAddress,proto3" json:"pickup_address,omitempty"`
	DeliveryAddress *Address               `protobuf:"bytes,3,opt,name=delivery_address,json=deliveryAddress,proto3" json:"delivery_address,omitempty"`
	Customer        *CustomerInfo          `protobuf:"bytes,4,opt,name=customer,proto3" json:"customer,omitempty"`
	Delivery        *DeliveryInfo          `protobuf:"bytes,5,opt,name=delivery,proto3" json:"delivery,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PackageFullDetails) Reset() {
	*x = PackageFullDetails{}
	mi := &file_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageFullDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageFullDetails) ProtoMessage() {}

func (x *PackageFullDetails) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageFullDetails.ProtoReflect.Descriptor instead.
func (*PackageFullDetails) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{3}
}

func (x *PackageFullDetails) GetPackage() *Package {
	if x != nil {
		return x.Package
	}
	return nil
}

func (x *PackageFullDetails) GetPickupAddress() *Address {
	if x != nil {
		return x.PickupAddress
	}
	return nil
}

func (x *PackageFullDetails) GetDeliveryAddress() *Address {
	if x != nil {
		return x.DeliveryAddress
	}
	return nil
}

func (x *PackageFullDetails) GetCustomer() *CustomerInfo {
	if x != nil {
		return x.Customer
	}
	return nil
}

func (x *PackageFullDetails) GetDelivery() *DeliveryInfo {
	if x != nil {
		return x.Delivery
	}
	return nil
}

type CustomerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	CompanyName   string                 `protobuf:"bytes,2,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomerInfo) Reset() {
	*x = CustomerInfo{}
	mi := &file_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerInfo) ProtoMessage() {}

func (x *CustomerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerInfo.ProtoReflect.Descriptor instead.
func (*CustomerInfo) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{4}
}

func (x *CustomerInfo) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CustomerInfo) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *CustomerInfo) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CustomerInfo) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CustomerInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CustomerInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type Delivery struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DeliveryId            string                 `protobuf:"bytes,2,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	PackageId             string                 `protobuf:"bytes,3,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	DriverId              string                 `protobuf:"bytes,4,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	RouteId               string                 `protobuf:"bytes,5,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	ScheduledPickupTime   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=scheduled_pickup_time,json=scheduledPickupTime,proto3" json:"scheduled_pickup_time,omitempty"`
	ActualPickupTime      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=actual_pickup_time,json=actualPickupTime,proto3" json:"actual_pickup_time,omitempty"`
	ScheduledDeliveryTime *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=scheduled_delivery_time,json=scheduledDeliveryTime,proto3" json:"scheduled_delivery_time,omitempty"`
	EstimatedDeliveryTime *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=estimated_delivery_time,json=estimatedDeliveryTime,proto3" json:"estimated_delivery_time,omitempty"`
	ActualDeliveryTime    *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=actual_delivery_time,json=actualDeliveryTime,proto3" json:"actual_delivery_time,omitempty"`
	DeliveryStatus        DeliveryStatus         `protobuf:"varint,11,opt,name=delivery_status,json=deliveryStatus,proto3,enum=order.DeliveryStatus" json:"delivery_status,omitempty"`
	DeliveryProof         string                 `protobuf:"bytes,12,opt,name=delivery_proof,json=deliveryProof,proto3" json:"delivery_proof,omitempty"`
	DeliveryNotes         string                 `protobuf:"bytes,13,opt,name=delivery_notes,json=deliveryNotes,proto3" json:"delivery_notes,omitempty"`
	FailureReason         string                 `protobuf:"bytes,14,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	DistanceKm            float64                `protobuf:"fixed64,15,opt,name=distance_km,json=distanceKm,proto3" json:"distance_km,omitempty"`
	DurationMinutes       int32                  `protobuf:"varint,16,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	CreatedAt             *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt             *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Delivery) Reset() {
	*x = Delivery{}
	mi := &file_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delivery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delivery) ProtoMessage() {}

func (x *Delivery) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delivery.ProtoReflect.Descriptor instead.
func (*Delivery) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{5}
}

func (x *Delivery) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Delivery) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *Delivery) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *Delivery) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *Delivery) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *Delivery) GetScheduledPickupTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledPickupTime
	}
	return nil
}

func (x *Delivery) GetActualPickupTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ActualPickupTime
	}
	return nil
}

func (x *Delivery) GetScheduledDeliveryTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledDeliveryTime
	}
	return nil
}

func (x *Delivery) GetEstimatedDeliveryTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EstimatedDeliveryTime
	}
	return nil
}

func (x *Delivery) GetActualDeliveryTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ActualDeliveryTime
	}
	return nil
}

func (x *Delivery) GetDeliveryStatus() DeliveryStatus {
	if x != nil {
		return x.DeliveryStatus
	}
	return DeliveryStatus_DELIVERY_STATUS_UNSPECIFIED
}

func (x *Delivery) GetDeliveryProof() string {
	if x != nil {
		return x.DeliveryProof
	}
	return ""
}

func (x *Delivery) GetDeliveryNotes() string {
	if x != nil {
		return x.DeliveryNotes
	}
	return ""
}

func (x *Delivery) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

func (x *Delivery) GetDistanceKm() float64 {
	if x != nil {
		return x.DistanceKm
	}
	return 0
}

func (x *Delivery) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

func (x *Delivery) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Delivery) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type DeliveryInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delivery      *Delivery              `protobuf:"bytes,1,opt,name=delivery,proto3" json:"delivery,omitempty"`
	Driver        *DriverInfo            `protobuf:"bytes,2,opt,name=driver,proto3" json:"driver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryInfo) Reset() {
	*x = DeliveryInfo{}
	mi := &file_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryInfo) ProtoMessage() {}

func (x *DeliveryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryInfo.ProtoReflect.Descriptor instead.
func (*DeliveryInfo) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{6}
}

func (x *DeliveryInfo) GetDelivery() *Delivery {
	if x != nil {
		return x.Delivery
	}
	return nil
}

func (x *DeliveryInfo) GetDriver() *DriverInfo {
	if x != nil {
		return x.Driver
	}
	return nil
}

type DriverInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	VehicleType   string                 `protobuf:"bytes,5,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`
	VehiclePlate  string                 `protobuf:"bytes,6,opt,name=vehicle_plate,json=vehiclePlate,proto3" json:"vehicle_plate,omitempty"`
	Rating        float64                `protobuf:"fixed64,7,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverInfo) Reset() {
	*x = DriverInfo{}
	mi := &file_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverInfo) ProtoMessage() {}

func (x *DriverInfo) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverInfo.ProtoReflect.Descriptor instead.
func (*DriverInfo) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{7}
}

func (x *DriverInfo) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *DriverInfo) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *DriverInfo) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *DriverInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *DriverInfo) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

func (x *DriverInfo) GetVehiclePlate() string {
	if x != nil {
		return x.VehiclePlate
	}
	return ""
}

func (x *DriverInfo) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

type DeliveryFullDetails struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Delivery        *Delivery              `protobuf:"bytes,1,opt,name=delivery,proto3" json:"delivery,omitempty"`
	Package         *Package               `protobuf:"bytes,2,opt,name=package,proto3" json:"package,omitempty"`
	PickupAddress   *Address               `protobuf:"bytes,3,opt,name=pickup_address,json=pickupAddress,proto3" json:"pickup_address,omitempty"`
	DeliveryAddress *Address               `protobuf:"bytes,4,opt,name=delivery_address,json=deliveryAddress,proto3" json:"delivery_address,omitempty"`
	Driver          *DriverInfo            `protobuf:"bytes,5,opt,name=driver,proto3" json:"driver,omitempty"`
	Customer        *CustomerInfo          `protobuf:"bytes,6,opt,name=customer,proto3" json:"customer,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeliveryFullDetails) Reset() {
	*x = DeliveryFullDetails{}
	mi := &file_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryFullDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryFullDetails) ProtoMessage() {}

func (x *DeliveryFullDetails) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryFullDetails.ProtoReflect.Descriptor instead.
func (*DeliveryFullDetails) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{8}
}

func (x *DeliveryFullDetails) GetDelivery() *Delivery {
	if x != nil {
		return x.Delivery
	}
	return nil
}

func (x *DeliveryFullDetails) GetPackage() *Package {
	if x != nil {
		return x.Package
	}
	return nil
}

func (x *DeliveryFullDetails) GetPickupAddress() *Address {
	if x != nil {
		return x.PickupAddress
	}
	return nil
}

func (x *DeliveryFullDetails) GetDeliveryAddress() *Address {
	if x != nil {
		return x.DeliveryAddress
	}
	return nil
}

func (x *DeliveryFullDetails) GetDriver() *DriverInfo {
	if x != nil {
		return x.Driver
	}
	return nil
}

func (x *DeliveryFullDetails) GetCustomer() *CustomerInfo {
	if x != nil {
		return x.Customer
	}
	return nil
}

type TrackingEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EventId          string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	PackageId        string                 `protobuf:"bytes,3,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	DeliveryId       string                 `protobuf:"bytes,4,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	EventType        TrackingEventType      `protobuf:"varint,5,opt,name=event_type,json=eventType,proto3,enum=order.TrackingEventType" json:"event_type,omitempty"`
	EventDescription string                 `protobuf:"bytes,6,opt,name=event_description,json=eventDescription,proto3" json:"event_description,omitempty"`
	Location         string                 `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	Latitude         float64                `protobuf:"fixed64,8,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude        float64                `protobuf:"fixed64,9,opt,name=longitude,proto3" json:"longitude,omitempty"`
	OccurredAt       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	CreatedBy        string                 `protobuf:"bytes,11,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TrackingEvent) Reset() {
	*x = TrackingEvent{}
	mi := &file_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackingEvent) ProtoMessage() {}

func (x *TrackingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackingEvent.ProtoReflect.Descriptor instead.
func (*TrackingEvent) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{9}
}

func (x *TrackingEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TrackingEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *TrackingEvent) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *TrackingEvent) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *TrackingEvent) GetEventType() TrackingEventType {
	if x != nil {
		return x.EventType
	}
	return TrackingEventType_TRACKING_EVENT_TYPE_UNSPECIFIED
}

func (x *TrackingEvent) GetEventDescription() string {
	if x != nil {
		return x.EventDescription
	}
	return ""
}

func (x *TrackingEvent) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *TrackingEvent) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *TrackingEvent) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *TrackingEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *TrackingEvent) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *TrackingEvent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Route struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Id                       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RouteId                  string                 `protobuf:"bytes,2,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	DriverId                 string                 `protobuf:"bytes,3,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	RouteName                string                 `protobuf:"bytes,4,opt,name=route_name,json=routeName,proto3" json:"route_name,omitempty"`
	StartLocation            string                 `protobuf:"bytes,5,opt,name=start_location,json=startLocation,proto3" json:"start_location,omitempty"`
	EndLocation              string                 `protobuf:"bytes,6,opt,name=end_location,json=endLocation,proto3" json:"end_location,omitempty"`
	Status                   string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	TotalDistanceKm          float64                `protobuf:"fixed64,8,opt,name=total_distance_km,json=totalDistanceKm,proto3" json:"total_distance_km,omitempty"`
	EstimatedDurationMinutes int32                  `protobuf:"varint,9,opt,name=estimated_duration_minutes,json=estimatedDurationMinutes,proto3" json:"estimated_duration_minutes,omitempty"`
	ActualDurationMinutes    int32                  `protobuf:"varint,10,opt,name=actual_duration_minutes,json=actualDurationMinutes,proto3" json:"actual_duration_minutes,omitempty"`
	OptimizationScore        float64                `protobuf:"fixed64,11,opt,name=optimization_score,json=optimizationScore,proto3" json:"optimization_score,omitempty"`
	StartedAt                *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt              *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	CreatedAt                *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt                *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{10}
}

func (x *Route) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Route) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *Route) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *Route) GetRouteName() string {
	if x != nil {
		return x.RouteName
	}
	return ""
}

func (x *Route) GetStartLocation() string {
	if x != nil {
		return x.StartLocation
	}
	return ""
}

func (x *Route) GetEndLocation() string {
	if x != nil {
		return x.EndLocation
	}
	return ""
}

func (x *Route) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Route) GetTotalDistanceKm() float64 {
	if x != nil {
		return x.TotalDistanceKm
	}
	return 0
}

func (x *Route) GetEstimatedDurationMinutes() int32 {
	if x != nil {
		return x.EstimatedDurationMinutes
	}
	return 0
}

func (x *Route) GetActualDurationMinutes() int32 {
	if x != nil {
		return x.ActualDurationMinutes
	}
	return 0
}

func (x *Route) GetOptimizationScore() float64 {
	if x != nil {
		return x.OptimizationScore
	}
	return 0
}

func (x *Route) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Route) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *Route) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Route) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type RouteStop struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StopId             string                 `protobuf:"bytes,2,opt,name=stop_id,json=stopId,proto3" json:"stop_id,omitempty"`
	RouteId            string                 `protobuf:"bytes,3,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	DeliveryId         string                 `protobuf:"bytes,4,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	StopSequence       int32                  `protobuf:"varint,5,opt,name=stop_sequence,json=stopSequence,proto3" json:"stop_sequence,omitempty"`
	StopType           string                 `protobuf:"bytes,6,opt,name=stop_type,json=stopType,proto3" json:"stop_type,omitempty"`
	AddressId          string                 `protobuf:"bytes,7,opt,name=address_id,json=addressId,proto3" json:"address_id,omitempty"`
	ScheduledArrival   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=scheduled_arrival,json=scheduledArrival,proto3" json:"scheduled_arrival,omitempty"`
	ActualArrival      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=actual_arrival,json=actualArrival,proto3" json:"actual_arrival,omitempty"`
	ScheduledDeparture *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=scheduled_departure,json=scheduledDeparture,proto3" json:"scheduled_departure,omitempty"`
	ActualDeparture    *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=actual_departure,json=actualDeparture,proto3" json:"actual_departure,omitempty"`
	Status             string                 `protobuf:"bytes,12,opt,name=status,proto3" json:"status,omitempty"`
	DwellTimeMinutes   int32                  `protobuf:"varint,13,opt,name=dwell_time_minutes,json=dwellTimeMinutes,proto3" json:"dwell_time_minutes,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RouteStop) Reset() {
	*x = RouteStop{}
	mi := &file_order_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteStop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteStop) ProtoMessage() {}

func (x *RouteStop) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteStop.ProtoReflect.Descriptor instead.
func (*RouteStop) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{11}
}

func (x *RouteStop) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RouteStop) GetStopId() string {
	if x != nil {
		return x.StopId
	}
	return ""
}

func (x *RouteStop) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *RouteStop) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *RouteStop) GetStopSequence() int32 {
	if x != nil {
		return x.StopSequence
	}
	return 0
}

func (x *RouteStop) GetStopType() string {
	if x != nil {
		return x.StopType
	}
	return ""
}

func (x *RouteStop) GetAddressId() string {
	if x != nil {
		return x.AddressId
	}
	return ""
}

func (x *RouteStop) GetScheduledArrival() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledArrival
	}
	return nil
}

func (x *RouteStop) GetActualArrival() *timestamppb.Timestamp {
	if x != nil {
		return x.ActualArrival
	}
	return nil
}

func (x *RouteStop) GetScheduledDeparture() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledDeparture
	}
	return nil
}

func (x *RouteStop) GetActualDeparture() *timestamppb.Timestamp {
	if x != nil {
		return x.ActualDeparture
	}
	return nil
}

func (x *RouteStop) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RouteStop) GetDwellTimeMinutes() int32 {
	if x != nil {
		return x.DwellTimeMinutes
	}
	return 0
}

func (x *RouteStop) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *RouteStop) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type RouteWithStops struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Route         *Route                 `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`
	Stops         []*RouteStop           `protobuf:"bytes,2,rep,name=stops,proto3" json:"stops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteWithStops) Reset() {
	*x = RouteWithStops{}
	mi := &file_order_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteWithStops) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteWithStops) ProtoMessage() {}

func (x *RouteWithStops) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteWithStops.ProtoReflect.Descriptor instead.
func (*RouteWithStops) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{12}
}

func (x *RouteWithStops) GetRoute() *Route {
	if x != nil {
		return x.Route
	}
	return nil
}

func (x *RouteWithStops) GetStops() []*RouteStop {
	if x != nil {
		return x.Stops
	}
	return nil
}

type PaginationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationRequest) Reset() {
	*x = PaginationRequest{}
	mi := &file_order_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationRequest) ProtoMessage() {}

func (x *PaginationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationRequest.ProtoReflect.Descriptor instead.
func (*PaginationRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{13}
}

func (x *PaginationRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginationRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type PaginationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationResponse) Reset() {
	*x = PaginationResponse{}
	mi := &file_order_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationResponse) ProtoMessage() {}

func (x *PaginationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationResponse.ProtoReflect.Descriptor instead.
func (*PaginationResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{14}
}

func (x *PaginationResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginationResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PaginationResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *PaginationResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_order_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{15}
}

func (x *Location) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Location) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Location) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type PriceEstimate struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	BasePrice           float64                `protobuf:"fixed64,1,opt,name=base_price,json=basePrice,proto3" json:"base_price,omitempty"`
	DistancePrice       float64                `protobuf:"fixed64,2,opt,name=distance_price,json=distancePrice,proto3" json:"distance_price,omitempty"`
	WeightPrice         float64                `protobuf:"fixed64,3,opt,name=weight_price,json=weightPrice,proto3" json:"weight_price,omitempty"`
	PriorityMultiplier  float64                `protobuf:"fixed64,4,opt,name=priority_multiplier,json=priorityMultiplier,proto3" json:"priority_multiplier,omitempty"`
	TotalPrice          float64                `protobuf:"fixed64,5,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	Currency            string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	EstimatedDistanceKm float64                `protobuf:"fixed64,7,opt,name=estimated_distance_km,json=estimatedDistanceKm,proto3" json:"estimated_distance_km,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PriceEstimate) Reset() {
	*x = PriceEstimate{}
	mi := &file_order_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceEstimate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceEstimate) ProtoMessage() {}

func (x *PriceEstimate) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceEstimate.ProtoReflect.Descriptor instead.
func (*PriceEstimate) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{16}
}

func (x *PriceEstimate) GetBasePrice() float64 {
	if x != nil {
		return x.BasePrice
	}
	return 0
}

func (x *PriceEstimate) GetDistancePrice() float64 {
	if x != nil {
		return x.DistancePrice
	}
	return 0
}

func (x *PriceEstimate) GetWeightPrice() float64 {
	if x != nil {
		return x.WeightPrice
	}
	return 0
}

func (x *PriceEstimate) GetPriorityMultiplier() float64 {
	if x != nil {
		return x.PriorityMultiplier
	}
	return 0
}

func (x *PriceEstimate) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *PriceEstimate) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PriceEstimate) GetEstimatedDistanceKm() float64 {
	if x != nil {
		return x.EstimatedDistanceKm
	}
	return 0
}

var File_order_proto protoreflect.FileDescriptor

const file_order_proto_rawDesc = "" +
	"\n" +
	"\vorder.proto\x12\x05order\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe6\x03\n" +
	"\aAddress\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"address_id\x18\x02 \x01(\tR\taddressId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x14\n" +
	"\x05label\x18\x04 \x01(\tR\x05label\x12%\n" +
	"\x0estreet_address\x18\x05 \x01(\tR\rstreetAddress\x12\x12\n" +
	"\x04city\x18\x06 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\a \x01(\tR\x05state\x12\x1f\n" +
	"\vpostal_code\x18\b \x01(\tR\n" +
	"postalCode\x12\x18\n" +
	"\acountry\x18\t \x01(\tR\acountry\x12\x1a\n" +
	"\blatitude\x18\n" +
	" \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\v \x01(\x01R\tlongitude\x12\"\n" +
	"\finstructions\x18\f \x01(\tR\finstructions\x12\x1d\n" +
	"\n" +
	"is_default\x18\r \x01(\bR\tisDefault\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x85\x05\n" +
	"\aPackage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"package_id\x18\x02 \x01(\tR\tpackageId\x12\x1f\n" +
	"\vcustomer_id\x18\x03 \x01(\tR\n" +
	"customerId\x12'\n" +
	"\x0ftracking_number\x18\x04 \x01(\tR\x0etrackingNumber\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x16\n" +
	"\x06weight\x18\x06 \x01(\x01R\x06weight\x12\x1e\n" +
	"\n" +
	"dimensions\x18\a \x01(\tR\n" +
	"dimensions\x122\n" +
	"\bcategory\x18\b \x01(\x0e2\x16.order.PackageCategoryR\bcategory\x12\x14\n" +
	"\x05value\x18\t \x01(\x01R\x05value\x122\n" +
	"\bpriority\x18\n" +
	" \x01(\x0e2\x16.order.PackagePriorityR\bpriority\x12)\n" +
	"\x10special_handling\x18\v \x01(\tR\x0fspecialHandling\x12*\n" +
	"\x11pickup_address_id\x18\f \x01(\tR\x0fpickupAddressId\x12.\n" +
	"\x13delivery_address_id\x18\r \x01(\tR\x11deliveryAddressId\x12,\n" +
	"\x06status\x18\x0e \x01(\x0e2\x14.order.PackageStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xb2\x01\n" +
	"\x14PackageWithAddresses\x12(\n" +
	"\apackage\x18\x01 \x01(\v2\x0e.order.PackageR\apackage\x125\n" +
	"\x0epickup_address\x18\x02 \x01(\v2\x0e.order.AddressR\rpickupAddress\x129\n" +
	"\x10delivery_address\x18\x03 \x01(\v2\x0e.order.AddressR\x0fdeliveryAddress\"\x92\x02\n" +
	"\x12PackageFullDetails\x12(\n" +
	"\apackage\x18\x01 \x01(\v2\x0e.order.PackageR\apackage\x125\n" +
	"\x0epickup_address\x18\x02 \x01(\v2\x0e.order.AddressR\rpickupAddress\x129\n" +
	"\x10delivery_address\x18\x03 \x01(\v2\x0e.order.AddressR\x0fdeliveryAddress\x12/\n" +
	"\bcustomer\x18\x04 \x01(\v2\x13.order.CustomerInfoR\bcustomer\x12/\n" +
	"\bdelivery\x18\x05 \x01(\v2\x13.order.DeliveryInfoR\bdelivery\"\xba\x01\n" +
	"\fCustomerInfo\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12!\n" +
	"\fcompany_name\x18\x02 \x01(\tR\vcompanyName\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x06 \x01(\tR\x05phone\"\x99\a\n" +
	"\bDelivery\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vdelivery_id\x18\x02 \x01(\tR\n" +
	"deliveryId\x12\x1d\n" +
	"\n" +
	"package_id\x18\x03 \x01(\tR\tpackageId\x12\x1b\n" +
	"\tdriver_id\x18\x04 \x01(\tR\bdriverId\x12\x19\n" +
	"\broute_id\x18\x05 \x01(\tR\arouteId\x12N\n" +
	"\x15scheduled_pickup_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x13scheduledPickupTime\x12H\n" +
	"\x12actual_pickup_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x10actualPickupTime\x12R\n" +
	"\x17scheduled_delivery_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x15scheduledDeliveryTime\x12R\n" +
	"\x17estimated_delivery_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x15estimatedDeliveryTime\x12L\n" +
	"\x14actual_delivery_time\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x12actualDeliveryTime\x12>\n" +
	"\x0fdelivery_status\x18\v \x01(\x0e2\x15.order.DeliveryStatusR\x0edeliveryStatus\x12%\n" +
	"\x0edelivery_proof\x18\f \x01(\tR\rdeliveryProof\x12%\n" +
	"\x0edelivery_notes\x18\r \x01(\tR\rdeliveryNotes\x12%\n" +
	"\x0efailure_reason\x18\x0e \x01(\tR\rfailureReason\x12\x1f\n" +
	"\vdistance_km\x18\x0f \x01(\x01R\n" +
	"distanceKm\x12)\n" +
	"\x10duration_minutes\x18\x10 \x01(\x05R\x0fdurationMinutes\x129\n" +
	"\n" +
	"created_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"f\n" +
	"\fDeliveryInfo\x12+\n" +
	"\bdelivery\x18\x01 \x01(\v2\x0f.order.DeliveryR\bdelivery\x12)\n" +
	"\x06driver\x18\x02 \x01(\v2\x11.order.DriverInfoR\x06driver\"\xdb\x01\n" +
	"\n" +
	"DriverInfo\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12!\n" +
	"\fvehicle_type\x18\x05 \x01(\tR\vvehicleType\x12#\n" +
	"\rvehicle_plate\x18\x06 \x01(\tR\fvehiclePlate\x12\x16\n" +
	"\x06rating\x18\a \x01(\x01R\x06rating\"\xba\x02\n" +
	"\x13DeliveryFullDetails\x12+\n" +
	"\bdelivery\x18\x01 \x01(\v2\x0f.order.DeliveryR\bdelivery\x12(\n" +
	"\apackage\x18\x02 \x01(\v2\x0e.order.PackageR\apackage\x125\n" +
	"\x0epickup_address\x18\x03 \x01(\v2\x0e.order.AddressR\rpickupAddress\x129\n" +
	"\x10delivery_address\x18\x04 \x01(\v2\x0e.order.AddressR\x0fdeliveryAddress\x12)\n" +
	"\x06driver\x18\x05 \x01(\v2\x11.order.DriverInfoR\x06driver\x12/\n" +
	"\bcustomer\x18\x06 \x01(\v2\x13.order.CustomerInfoR\bcustomer\"\xcd\x03\n" +
	"\rTrackingEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"package_id\x18\x03 \x01(\tR\tpackageId\x12\x1f\n" +
	"\vdelivery_id\x18\x04 \x01(\tR\n" +
	"deliveryId\x127\n" +
	"\n" +
	"event_type\x18\x05 \x01(\x0e2\x18.order.TrackingEventTypeR\teventType\x12+\n" +
	"\x11event_description\x18\x06 \x01(\tR\x10eventDescription\x12\x1a\n" +
	"\blocation\x18\a \x01(\tR\blocation\x12\x1a\n" +
	"\blatitude\x18\b \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\t \x01(\x01R\tlongitude\x12;\n" +
	"\voccurred_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\v \x01(\tR\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x91\x05\n" +
	"\x05Route\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\broute_id\x18\x02 \x01(\tR\arouteId\x12\x1b\n" +
	"\tdriver_id\x18\x03 \x01(\tR\bdriverId\x12\x1d\n" +
	"\n" +
	"route_name\x18\x04 \x01(\tR\trouteName\x12%\n" +
	"\x0estart_location\x18\x05 \x01(\tR\rstartLocation\x12!\n" +
	"\fend_location\x18\x06 \x01(\tR\vendLocation\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12*\n" +
	"\x11total_distance_km\x18\b \x01(\x01R\x0ftotalDistanceKm\x12<\n" +
	"\x1aestimated_duration_minutes\x18\t \x01(\x05R\x18estimatedDurationMinutes\x126\n" +
	"\x17actual_duration_minutes\x18\n" +
	" \x01(\x05R\x15actualDurationMinutes\x12-\n" +
	"\x12optimization_score\x18\v \x01(\x01R\x11optimizationScore\x129\n" +
	"\n" +
	"started_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xad\x05\n" +
	"\tRouteStop\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\astop_id\x18\x02 \x01(\tR\x06stopId\x12\x19\n" +
	"\broute_id\x18\x03 \x01(\tR\arouteId\x12\x1f\n" +
	"\vdelivery_id\x18\x04 \x01(\tR\n" +
	"deliveryId\x12#\n" +
	"\rstop_sequence\x18\x05 \x01(\x05R\fstopSequence\x12\x1b\n" +
	"\tstop_type\x18\x06 \x01(\tR\bstopType\x12\x1d\n" +
	"\n" +
	"address_id\x18\a \x01(\tR\taddressId\x12G\n" +
	"\x11scheduled_arrival\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x10scheduledArrival\x12A\n" +
	"\x0eactual_arrival\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\ractualArrival\x12K\n" +
	"\x13scheduled_departure\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x12scheduledDeparture\x12E\n" +
	"\x10actual_departure\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\x0factualDeparture\x12\x16\n" +
	"\x06status\x18\f \x01(\tR\x06status\x12,\n" +
	"\x12dwell_time_minutes\x18\r \x01(\x05R\x10dwellTimeMinutes\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\\\n" +
	"\x0eRouteWithStops\x12\"\n" +
	"\x05route\x18\x01 \x01(\v2\f.order.RouteR\x05route\x12&\n" +
	"\x05stops\x18\x02 \x03(\v2\x10.order.RouteStopR\x05stops\"D\n" +
	"\x11PaginationRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\x87\x01\n" +
	"\x12PaginationResponse\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPages\"^\n" +
	"\bLocation\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\"\x9a\x02\n" +
	"\rPriceEstimate\x12\x1d\n" +
	"\n" +
	"base_price\x18\x01 \x01(\x01R\tbasePrice\x12%\n" +
	"\x0edistance_price\x18\x02 \x01(\x01R\rdistancePrice\x12!\n" +
	"\fweight_price\x18\x03 \x01(\x01R\vweightPrice\x12/\n" +
	"\x13priority_multiplier\x18\x04 \x01(\x01R\x12priorityMultiplier\x12\x1f\n" +
	"\vtotal_price\x18\x05 \x01(\x01R\n" +
	"totalPrice\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x122\n" +
	"\x15estimated_distance_km\x18\a \x01(\x01R\x13estimatedDistanceKm*\x84\x02\n" +
	"\rPackageStatus\x12\x1e\n" +
	"\x1aPACKAGE_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PACKAGE_STATUS_PENDING\x10\x01\x12\x1c\n" +
	"\x18PACKAGE_STATUS_PICKED_UP\x10\x02\x12\x1d\n" +
	"\x19PACKAGE_STATUS_IN_TRANSIT\x10\x03\x12#\n" +
	"\x1fPACKAGE_STATUS_OUT_FOR_DELIVERY\x10\x04\x12\x1c\n" +
	"\x18PACKAGE_STATUS_DELIVERED\x10\x05\x12\x19\n" +
	"\x15PACKAGE_STATUS_FAILED\x10\x06\x12\x1c\n" +
	"\x18PACKAGE_STATUS_CANCELLED\x10\a*\x8e\x01\n" +
	"\x0fPackagePriority\x12 \n" +
	"\x1cPACKAGE_PRIORITY_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18PACKAGE_PRIORITY_ECONOMY\x10\x01\x12\x1d\n" +
	"\x19PACKAGE_PRIORITY_STANDARD\x10\x02\x12\x1c\n" +
	"\x18PACKAGE_PRIORITY_EXPRESS\x10\x03*\xeb\x01\n" +
	"\x0fPackageCategory\x12 \n" +
	"\x1cPACKAGE_CATEGORY_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aPACKAGE_CATEGORY_DOCUMENTS\x10\x01\x12 \n" +
	"\x1cPACKAGE_CATEGORY_ELECTRONICS\x10\x02\x12\x19\n" +
	"\x15PACKAGE_CATEGORY_FOOD\x10\x03\x12\x1c\n" +
	"\x18PACKAGE_CATEGORY_FRAGILE\x10\x04\x12\x1d\n" +
	"\x19PACKAGE_CATEGORY_CLOTHING\x10\x05\x12\x1c\n" +
	"\x18PACKAGE_CATEGORY_GENERAL\x10\x06*\xca\x01\n" +
	"\x0eDeliveryStatus\x12\x1f\n" +
	"\x1bDELIVERY_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18DELIVERY_STATUS_ASSIGNED\x10\x01\x12\x1f\n" +
	"\x1bDELIVERY_STATUS_IN_PROGRESS\x10\x02\x12\x1d\n" +
	"\x19DELIVERY_STATUS_COMPLETED\x10\x03\x12\x1a\n" +
	"\x16DELIVERY_STATUS_FAILED\x10\x04\x12\x1d\n" +
	"\x19DELIVERY_STATUS_CANCELLED\x10\x05*\xd5\x02\n" +
	"\x11TrackingEventType\x12#\n" +
	"\x1fTRACKING_EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bTRACKING_EVENT_TYPE_CREATED\x10\x01\x12 \n" +
	"\x1cTRACKING_EVENT_TYPE_ASSIGNED\x10\x02\x12!\n" +
	"\x1dTRACKING_EVENT_TYPE_PICKED_UP\x10\x03\x12\"\n" +
	"\x1eTRACKING_EVENT_TYPE_IN_TRANSIT\x10\x04\x12(\n" +
	"$TRACKING_EVENT_TYPE_OUT_FOR_DELIVERY\x10\x05\x12!\n" +
	"\x1dTRACKING_EVENT_TYPE_DELIVERED\x10\x06\x12!\n" +
	"\x1dTRACKING_EVENT_TYPE_EXCEPTION\x10\a\x12!\n" +
	"\x1dTRACKING_EVENT_TYPE_CANCELLED\x10\bB\x1aZ\x18github.com/iambasill/streamfleet/pb/orderb\x06proto3"

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData []byte
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)))
	})
	return file_order_proto_rawDescData
}

var file_order_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_order_proto_goTypes = []any{
	(PackageStatus)(0),            // 0: order.PackageStatus
	(PackagePriority)(0),          // 1: order.PackagePriority
	(PackageCategory)(0),          // 2: order.PackageCategory
	(DeliveryStatus)(0),           // 3: order.DeliveryStatus
	(TrackingEventType)(0),        // 4: order.TrackingEventType
	(*Address)(nil),               // 5: order.Address
	(*Package)(nil),               // 6: order.Package
	(*PackageWithAddresses)(nil),  // 7: order.PackageWithAddresses
	(*PackageFullDetails)(nil),    // 8: order.PackageFullDetails
	(*CustomerInfo)(nil),          // 9: order.CustomerInfo
	(*Delivery)(nil),              // 10: order.Delivery
	(*DeliveryInfo)(nil),          // 11: order.DeliveryInfo
	(*DriverInfo)(nil),            // 12: order.DriverInfo
	(*DeliveryFullDetails)(nil),   // 13: order.DeliveryFullDetails
	(*TrackingEvent)(nil),         // 14: order.TrackingEvent
	(*Route)(nil),                 // 15: order.Route
	(*RouteStop)(nil),             // 16: order.RouteStop
	(*RouteWithStops)(nil),        // 17: order.RouteWithStops
	(*PaginationRequest)(nil),     // 18: order.PaginationRequest
	(*PaginationResponse)(nil),    // 19: order.PaginationResponse
	(*Location)(nil),              // 20: order.Location
	(*PriceEstimate)(nil),         // 21: order.PriceEstimate
	(*timestamppb.Timestamp)(nil), // 22: google.protobuf.Timestamp
}
var file_order_proto_depIdxs = []int32{
	22, // 0: order.Address.created_at:type_name -> google.protobuf.Timestamp
	22, // 1: order.Address.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 2: order.Package.category:type_name -> order.PackageCategory
	1,  // 3: order.Package.priority:type_name -> order.PackagePriority
	0,  // 4: order.Package.status:type_name -> order.PackageStatus
	22, // 5: order.Package.created_at:type_name -> google.protobuf.Timestamp
	22, // 6: order.Package.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 7: order.PackageWithAddresses.package:type_name -> order.Package
	5,  // 8: order.PackageWithAddresses.pickup_address:type_name -> order.Address
	5,  // 9: order.PackageWithAddresses.delivery_address:type_name -> order.Address
	6,  // 10: order.PackageFullDetails.package:type_name -> order.Package
	5,  // 11: order.PackageFullDetails.pickup_address:type_name -> order.Address
	5,  // 12: order.PackageFullDetails.delivery_address:type_name -> order.Address
	9,  // 13: order.PackageFullDetails.customer:type_name -> order.CustomerInfo
	11, // 14: order.PackageFullDetails.delivery:type_name -> order.DeliveryInfo
	22, // 15: order.Delivery.scheduled_pickup_time:type_name -> google.protobuf.Timestamp
	22, // 16: order.Delivery.actual_pickup_time:type_name -> google.protobuf.Timestamp
	22, // 17: order.Delivery.scheduled_delivery_time:type_name -> google.protobuf.Timestamp
	22, // 18: order.Delivery.estimated_delivery_time:type_name -> google.protobuf.Timestamp
	22, // 19: order.Delivery.actual_delivery_time:type_name -> google.protobuf.Timestamp
	3,  // 20: order.Delivery.delivery_status:type_name -> order.DeliveryStatus
	22, // 21: order.Delivery.created_at:type_name -> google.protobuf.Timestamp
	22, // 22: order.Delivery.updated_at:type_name -> google.protobuf.Timestamp
	10, // 23: order.DeliveryInfo.delivery:type_name -> order.Delivery
	12, // 24: order.DeliveryInfo.driver:type_name -> order.DriverInfo
	10, // 25: order.DeliveryFullDetails.delivery:type_name -> order.Delivery
	6,  // 26: order.DeliveryFullDetails.package:type_name -> order.Package
	5,  // 27: order.DeliveryFullDetails.pickup_address:type_name -> order.Address
	5,  // 28: order.DeliveryFullDetails.delivery_address:type_name -> order.Address
	12, // 29: order.DeliveryFullDetails.driver:type_name -> order.DriverInfo
	9,  // 30: order.DeliveryFullDetails.customer:type_name -> order.CustomerInfo
	4,  // 31: order.TrackingEvent.event_type:type_name -> order.TrackingEventType
	22, // 32: order.TrackingEvent.occurred_at:type_name -> google.protobuf.Timestamp
	22, // 33: order.TrackingEvent.created_at:type_name -> google.protobuf.Timestamp
	22, // 34: order.Route.started_at:type_name -> google.protobuf.Timestamp
	22, // 35: order.Route.completed_at:type_name -> google.protobuf.Timestamp
	22, // 36: order.Route.created_at:type_name -> google.protobuf.Timestamp
	22, // 37: order.Route.updated_at:type_name -> google.protobuf.Timestamp
	22, // 38: order.RouteStop.scheduled_arrival:type_name -> google.protobuf.Timestamp
	22, // 39: order.RouteStop.actual_arrival:type_name -> google.protobuf.Timestamp
	22, // 40: order.RouteStop.scheduled_departure:type_name -> google.protobuf.Timestamp
	22, // 41: order.RouteStop.actual_departure:type_name -> google.protobuf.Timestamp
	22, // 42: order.RouteStop.created_at:type_name -> google.protobuf.Timestamp
	22, // 43: order.RouteStop.updated_at:type_name -> google.protobuf.Timestamp
	15, // 44: order.RouteWithStops.route:type_name -> order.Route
	16, // 45: order.RouteWithStops.stops:type_name -> order.RouteStop
	46, // [46:46] is the sub-list for method output_type
	46, // [46:46] is the sub-list for method input_type
	46, // [46:46] is the sub-list for extension type_name
	46, // [46:46] is the sub-list for extension extendee
	0,  // [0:46] is the sub-list for field type_name
}

func init() { file_order_proto_init() }
func file_order_proto_init() {
	if File_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_order_proto_goTypes,
		DependencyIndexes: file_order_proto_depIdxs,
		EnumInfos:         file_order_proto_enumTypes,
		MessageInfos:      file_order_proto_msgTypes,
	}.Build()
	File_order_proto = out.File
	file_order_proto_goTypes = nil
	file_order_proto_depIdxs = nil
}
